import 'localization_keys.dart';

final Map<String, String> bho = {
  appName: 'भाषावर्स',
  selectAppLanguage: 'एप्प के भाषा चुनी',
  youCanAlwaysChange: 'रउआ सेटिंग के कबो भी बदल सकsतानी ',
  searchLanguage: 'खोजे के भाषा',
  continueText: 'चालू रखीं',
  next: 'आगे के',
  skip: 'छोड़ दs',
  getStarted: 'शुरू करीं',
  speechRecognition: 'भाषण के पहचान के बारे में बतावल गइल बा',
  automaticallyRecognizeAndConvert:
      'स्वचालित रूप से पहचान आउर अपना आवाज के पाठ में बदल देला',
  speechToSpeechTranslation: 'भाषण से भाषण के अनुवाद कइल जाला',
  translateYourVoiceInOneIndianLanguage:
      'आपन आवाज के एगो भारतीय भाषा से दोसर भाषा में अनुवाद करीं',
  languageTranslation: 'भाषा के अनुवाद',
  translateSentencesFromOneIndianLanguageToAnother:
      'एगो भारतीय भाषा से दोसर भाषा में वाक्य के अनुवाद करीं',
  bhashaverseChatBot: 'भाषावर्स चैट बॉट',
  selectVoiceAssistant: 'आवाज सहायक अवतार के चुनीं',
  youWillHearTheTranslationText:
      'रउरा जवन अवतार के चुनले बानी ऊहे आवाज में अनुवाद सुनाई दिही ,रउरा हमेशा से सेटिंग्स के बदल सकेनी',
  male: 'मरद',
  female: 'मेहरारू',
  letsTranslate: 'चलीं अनुवाद कइल जाव',
  appTheme: 'ऐप के थीम बा',
  appInterfaceWillChange: 'एप इंटरफेस तदनुसार चुनल मोड में बदल जाई',
  light: 'हलुक',
  dark: 'अन्हरिया',
  systemDefault: 'सिस्टम डिफ़ॉल्ट रूप से बा',
  appLanguage: 'एप भाषा',
  appInterfaceWillChangeInSelected: 'एप इंटरफेस चुनल एप भाषा में बदल जाइ',
  voiceAssistant: 'आवाज के सहायक के रूप में',
  transLiteration: 'लिप्यंतरण के काम कइल जाला',
  transLiterationWillInitiateWord:
      'लिप्यंतरण रउरा टाइप करे समय शब्द के सुझाव करी',
  advanceSettings: 'उन्नत्ति समायोजन',
  kTranslation: 'अनुवाद',
  kChat: 'बातचित',
  kSettings: 'समायोजन',
  kHomeLoadingAnimationText: 'रुकीं,हम रउरा खातिर काम के समायोजन करतानी',
  kTranslateSourceTitle: 'इंहा से अनुवाद करे के बा',
  kTranslateTargetTitle: 'एकराके अनुवाद करेके बा',
  kTranslationHintText: 'टाइपिंग शुरू करीं भा शुरू करे खातिर माइक दबाईं',
  kListeningHintText: 'सुनी अब रउआ बोले के शुरू करीं',
  kPaste: 'पेस्ट',
  kTranslate: 'अनुवाद',
  kReset: 'दुबारा से समायोजन',
  kErrorNoSourceText: 'कृपया पहिले पाठ दर्ज करीं',
  kErrorSelectSourceAndTargetScreen:
      'कृपया पहिले स्रोत आउर लक्ष्य भाषा के चुनीं',
  errorMicPermission: 'आवाज के रिकॉर्ड करे खातिर माइक के अनुमति के जरुरत बा',
  errorInRecording: 'आवाज रिकॉर्डिंग में गलती हो गइल बा',
  noVoiceAssistantAvailable: 'इ समय में कोनो ध्वनि सहायक उपलब्ध नइखे',
  kTranslationLoadingAnimationText: 'अनुवाद  होता ,कृपया प्रतीक्षा करीं',
  errorPleaseSelectLanguage: 'कृपया भाषा चुनीं',
  featureAvailableSoonInfo: 'ई सुविधा तुरत उपलब्ध होई',
  errorSelectVoiceAssistant: 'कृपया ध्वनि सहायक के अवतार चुनीं',
  noTextForShare: 'बाटें खातिर कवनो पाठ नइखे मिलल',
  noTextForCopy: 'प्रतिलिपि करे खातिर कवनो पाठ नइखे मिलल',
  textCopiedToClipboard: 'क्लिपबोर्ड पर पाठ के प्रतिलिपि कइल गइल',
  femaleVoiceAssistantNotAvailable:
      'मेहरारू के आवाज में ध्वनि सहायक उपलब्ध नइखे, मरद के ध्वनि सहायक चल रहल बा',
  maleVoiceAssistantNotAvailable:
      'मरद के ध्वनि सहायक नइखे,मेहरारू के ध्वनि सहायक चल रहल बा',
  errorNoTextInClipboard: 'क्लिपबोर्ड में कवनो पाठ उपलब्ध नइखे',
  s2sStreaming: 'एस टु एस स्ट्रीमिंग ',
  connecting: 'जुड़ रहल बा ',
  somethingWentWrong: 'कोनो दिक्कत हो गइल ',
  tapAndHoldForRecording: 'रिकॉर्डिंग करेके खातिर माइक के पकड़ के धइले रहीं। ',
  cannotPlayAudioAtTheMoment: 'अभी ऑडियो ना चल सकता ',
  responseNotReceived: 'गलती :प्रतिक्रिया नइखे मिलल। ',
  translationNotPossible: 'अभी अनुवाद सम्भव नइखे। ',
  bhashiniTitle: 'भाषिणी ',
};
