import 'localization_keys.dart';

final Map<String, String> bn = {
  appName: 'ভাষাভার্স',
  selectAppLanguage: 'অ্যাপের ভাষা নির্বাচন করুন',
  youCanAlwaysChange: 'আপনি সেটিংস থেকে তা বদল করতে পারেন',
  searchLanguage: 'সন্ধানের ভাষা',
  continueText: 'এগোতে থাকুন',
  next: 'পরবর্তী',
  skip: 'এড়িয়ে চলুন',
  getStarted: 'আরম্ভ করুন',
  speechRecognition: 'বাচন পরিচিতি',
  automaticallyRecognizeAndConvert:
      'আপনার স্বরকে চিহ্নিত করে তাকে স্বতন্ত্রভাবে লেখায় পাল্টে দেবে',
  speechToSpeechTranslation: 'বাচন থেকে বাচনে ভাষান্তর',
  translateYourVoiceInOneIndianLanguage:
      ' একটি ভারতীয় ভাষায় বলা কথা অপর একটিতে ভাষান্তর করুন ',
  languageTranslation: 'ভাষাগত অনুবাদ',
  translateSentencesFromOneIndianLanguageToAnother:
      'ভারতীয় ভাষার একটি বাক্য অপর একটিতে ভাষান্তর করুন',
  bhashaverseChatBot: 'ভাষাভার্স চ্যাট বট',
  selectVoiceAssistant: 'স্বর-সহায়ক অবতার নির্বাচন করুন',
  youWillHearTheTranslationText:
      'আপনার নির্বাচিত অবতারেই আপনি ভাষান্তরটি শুনতে পারবেন। সেটিংসে গিয়ে আপনি যেকোনোও সময় অবতারটি বদলাতে পারেন।',
  male: 'পুরুষ',
  female: 'মহিলা',
  letsTranslate: 'ভাষান্তর শুরু করা যাক',
  appTheme: 'অ্যাপের থিম',
  appInterfaceWillChange: 'নির্বাচিত মোডে অ্যাপের আদল বদলে যাবে',
  light: 'হালকা',
  dark: 'গাঢ়',
  systemDefault: 'পূর্বনির্ধারিত সিস্টেম',
  appLanguage: 'অ্যাপের ভাষা',
  appInterfaceWillChangeInSelected: 'নির্বাচিত ভাষায় অ্যাপের আদল বদলে যাবে',
  voiceAssistant: 'স্বর সহায়ক',
  transLiteration: 'লিপি-অন্তর',
  transLiterationWillInitiateWord:
      'লিপি-অন্তর আপনাকে টাইপ করার সময়ে নানা শব্দের প্রস্তাব দেবে',
  advanceSettings: 'উন্নত সেটিংস',
  kTranslation: 'অনুুবাদ',
  kChat: 'চ্যাট',
  kSettings: ' সেটিংস',
  kHomeLoadingAnimationText: 'অপেক্ষা করুন, আমরা আপনার জন্য সবকিছু সেট করছি',
  kTranslateSourceTitle: 'মূল ভাষা',
  kTranslateTargetTitle: 'অনুবাদের ভাষা',
  kTranslationHintText: 'টাইপ করতে থাকুন বা মাইক চিহ্ন টিপে শুরু করুন',
  kListeningHintText: 'শোনা চলছে, এবার বলুন',
  kPaste: 'পেস্ট করুন',
  kTranslate: 'অনুুবাদ করুন',
  kReset: 'রিসেট করুন',
  kErrorNoSourceText: 'দয়া করে প্রথমে টেক্সট এণ্টার করুন',
  kErrorSelectSourceAndTargetScreen:
      'দয়া করে প্রথমে মূল ভাষা ও অনুবাদের ভাষা নির্বাচন করুন ',
  errorMicPermission: 'রেকর্ড করতে মাইক অনুমতি প্রয়োজন',
  errorInRecording: 'স্বর রেকর্ডিংয়ে ভুল',
  noVoiceAssistantAvailable: 'এই মুহূর্তে কোনোও স্বর সহায়কের প্রয়োজন নেই',
  kTranslationLoadingAnimationText: 'ভাষান্তর চলছে, অপেক্ষা করুন',
  errorPleaseSelectLanguage: 'দয়া করে ভাষা নির্বাচন করুন',
  featureAvailableSoonInfo: 'এই সুবিধা শীঘ্রই যোগ করা হবে ',
  errorSelectVoiceAssistant: 'দয়া করে স্বর সহায়ক অবতার নির্বাচন করুন',
  noTextForShare: 'শেয়ার করার জন্য টেক্সট উপলব্ধ নেই',
  noTextForCopy: 'কপি করার জন্য টেক্সট উপলব্ধ নেই',
  textCopiedToClipboard: 'ক্লিপবোর্ডে টেক্সট কপি করা হয়েছে',
  femaleVoiceAssistantNotAvailable:
      'মহিলা স্বর সহায়ক উপলব্ধ নেই, পুরুষ স্বর সহায়ক ব্যবহার করা হচ্ছে',
  maleVoiceAssistantNotAvailable:
      'পুরুষ স্বর সহায়ক উপলব্ধ নেই, মহিলা স্বর সহায়ক ব্যবহার করা হচ্ছে',
  errorNoTextInClipboard: 'ক্লিপবোর্ডে কোনও টেক্সট নেই',
  s2sStreaming: 'এস-টু-এস স্ট্রিমিং',
  connecting: 'সংযোগ হচ্ছে...',
  somethingWentWrong: 'কিছু ভুলভ্রান্তি ঘটেছে',
  tapAndHoldForRecording: 'রেকর্ড করার জন্য মাইকে ট্যাপ করুন এবং ধরে থাকুন',
  cannotPlayAudioAtTheMoment: 'এই মুহূর্তে অডিওটি চালানো সম্ভব নয়',
  responseNotReceived: 'ভ্রান্তি: জবাব পাওয়া যায়নি',
  translationNotPossible: 'এই মুহূর্তে ভাষান্তর সম্ভব নয়',
  bhashiniTitle: 'ভাষিণী',
};
