import 'localization_keys.dart';

final Map<String, String> doi = {
  appName: 'भाशावर्स',
  selectAppLanguage: 'ऐप भाशा चुनो',
  youCanAlwaysChange: 'तुस इसगी सैट्टिंगें च म्हेशा बदली सकदे ओ',
  searchLanguage: 'भाशा खोजो',
  continueText: 'जारी रक्खो',
  next: 'अगला',
  skip: 'छोड़ी देओ',
  getStarted: 'शुरू करो',
  speechRecognition: 'स्पीच रीकग्नीशन',
  automaticallyRecognizeAndConvert:
      'अपनी अवाज गी आटोमैटिक तरीके कन्नै पन्छानो ते अबारत च बदलो',
  speechToSpeechTranslation: 'वाक्-शा-वाक् अनुवाद',
  translateYourVoiceInOneIndianLanguage:
      'अपनी अवाज गी इक भारती भाशा थमां दूई च अनूदत करो',
  languageTranslation: 'भाशा अनुवाद',
  translateSentencesFromOneIndianLanguageToAnother:
      'इक भारती भाशा दे वाक्यें गी दूई भाशा च अनूदत करो',
  bhashaverseChatBot: 'भासावर्स चैट बोट',
  selectVoiceAssistant: 'वाइस असिस्टैंट अवतार चुनो',
  youWillHearTheTranslationText:
      'तुसें गी अनुवाद उस अवतार दी अवाज च सनोग जेह्‌ड़ा तुसें चुनेआ ऐ । तुस अवतार गी सैट्टिंगें च म्हेशा बदली सकदे ओ',
  male: 'पुरश',
  female: 'महिला',
  letsTranslate: 'आओ, अनुवाद करचै',
  appTheme: 'ऐप थीम',
  appInterfaceWillChange: 'ऐप इंटरफेस चुनिंदा मोड दे मताबक बदली जाग',
  light: 'फिक्का',
  dark: 'गूढ़ा',
  systemDefault: 'डिफाल्ट सिस्टम',
  appLanguage: 'ऐप भाशा',
  appInterfaceWillChangeInSelected: 'ऐप इंटरफेस चुनिंदा ऐप भाशा च बदली जाग',
  voiceAssistant: 'वाइस असिस्टैंट',
  transLiteration: 'लिप्यंतरण',
  transLiterationWillInitiateWord:
      'तुस जिसलै टाइप करदेओ लिप्यंतरण शब्द-सुझाऽ शुरू करी देग',
  advanceSettings: 'उच्च सैट्टिंगां',
  kTranslation: 'अनुवाद',
  kChat: 'चैट',
  kSettings: 'सैट्टिंगां',
  kHomeLoadingAnimationText: 'रुको, अस तुं\'दे आस्तै चीजां सैट्ट करा करने आं',
  kTranslateSourceTitle: 'शा अनुवाद करो',
  kTranslateTargetTitle: 'च अनुवाद करो',
  kTranslationHintText: 'टाइप करना शुरू करो जां शुरू करने लेई माइक दबाओ',
  kListeningHintText: 'सुना करने आं, हुन बोल्लो',
  kPaste: 'पेस्ट करो',
  kTranslate: 'अनुवाद करो',
  kReset: 'परतियै सैट्ट करो',
  kErrorNoSourceText: 'कृपा करियै पैह्‌लें अबारत पाओ',
  kErrorSelectSourceAndTargetScreen:
      'कृपा करियै पैह्‌लें स्रोत ते लक्ष भाशा चुनो',
  errorMicPermission: 'ध्वनि दी रिकार्डिंग आस्तै माइक दी अनुमति लोड़दी ऐ',
  errorInRecording: 'अवाज दी रिकार्डिंग च त्रुट्टी',
  noVoiceAssistantAvailable: 'इसलै कोई वाइस असिस्टैंट उपलब्ध नेईं',
  kTranslationLoadingAnimationText: 'अनुवाद होआ करदा ऐ, कृपा करियै बलगो',
  errorPleaseSelectLanguage: 'कृपा करियै भाशा चुनो',
  featureAvailableSoonInfo: 'एह् फीचर तौले गै उपलब्ध होग',
  errorSelectVoiceAssistant: 'कृपा करियै वाइय असिस्टैंट अवतार चुनो',
  noTextForShare: 'शेयर करने गित्तै कोई अबारत नेईं लब्भी',
  noTextForCopy: 'कापी करने गित्तै कोई अबारत नेईं लब्भी',
  textCopiedToClipboard: 'अबारत गी क्लिपबोर्ड उप्पर कापी करी दित्ता',
  femaleVoiceAssistantNotAvailable:
      'महिला वाइस असिस्टैंट उपलब्ध नेईं ऐ, पुरश वाइस असिस्टैंट थमां चलाऽ करने',
  maleVoiceAssistantNotAvailable:
      'पुरश वाइस असिस्टैंट उपलब्ध नेईं ऐ, महिला वाइस असिस्टैंट थमां चलाऽ करने',
  errorNoTextInClipboard: 'क्लिप बोर्ड उप्पर कोई अबारत उपलब्ध नेई',
  s2sStreaming: 'एस2 एस स्ट्रीमिंग',
  connecting: 'कनेक्ट कीता जा’रदा ऐ . . . ',
  somethingWentWrong: 'किश गड़बड़ होई ऐ',
  tapAndHoldForRecording: 'रिकार्ड करने आस्तै टैप करो ते माइक गी फड़ियै रक्खो',
  cannotPlayAudioAtTheMoment: ' इस बेल्लै ऑडियो नेईं चलाया जाई सकदा',
  responseNotReceived: 'गलती - कोई जवाबी-कारवाई नेईं मिली',
  translationNotPossible: ' इस बेल्लै तरजमा मुमकन नेईं ऐ',
  bhashiniTitle: 'भाशिणी ',
};
