import 'localization_keys.dart';

final Map<String, String> en = {
  appName: 'Bhashaverse',
  selectAppLanguage: 'Select App Language',
  youCanAlwaysChange: 'You can always change this from settings.',
  searchLanguage: 'Search language',
  continueText: 'Continue',
  next: 'Next',
  skip: 'Skip',
  getStarted: 'Get started',
  speechRecognition: 'Speech Recognition',
  automaticallyRecognizeAndConvert:
      'Automatically recognize and convert your voice into text',
  speechToSpeechTranslation: 'Speech to Speech Translation',
  translateYourVoiceInOneIndianLanguage:
      'Translate your voice in one Indian language to another',
  languageTranslation: 'Language Translation',
  translateSentencesFromOneIndianLanguageToAnother:
      'Translate sentences from one Indian language to another',
  bhashaverseChatBot: 'Bhashaverse Chat bot',
  bhashiniChatBot: 'Bhashini Chat bot',
  selectVoiceAssistant: 'Select Voice Assistant Avatar',
  youWillHearTheTranslationText:
      'You will hear the translation in the voice of the avatar you selected. You can always change avatar from settings.',
  male: 'Male',
  female: 'Female',
  letsTranslate: 'Let’s translate',
  appTheme: 'App Theme',
  appInterfaceWillChange:
      'App interface will change in selected mode accordingly',
  light: 'Light',
  dark: 'Dark',
  systemDefault: 'System Default',
  appLanguage: 'App Language',
  appInterfaceWillChangeInSelected:
      'App interface will change in selected app language.',
  voiceAssistant: 'Voice Assistant',
  transLiteration: 'Transliteration',
  transLiterationWillInitiateWord:
      'Transliteration will initiate word suggestions while you type',
  advanceSettings: 'Advanced Settings',
  kTranslation: 'Translation',
  kChat: 'Chat',
  kSettings: 'Settings',
  kHomeLoadingAnimationText: 'Hold on, we are setting up things for you...',
  kTranslateSourceTitle: 'Translate from',
  kTranslateTargetTitle: 'Translate to',
  kTranslationHintText: 'Start typing or press mic to begin',
  kListeningHintText: 'Listening, Speak now...',
  kPaste: 'Paste',
  kTranslate: 'Translate',
  kReset: 'Reset',
  kErrorNoSourceText: 'Please enter text first',
  errorSelectSourceLangFirst: 'Please select source language first',
  kErrorSelectSourceAndTargetScreen:
      'Please select source and target language first',
  errorMicPermission: 'Mic permission required for recording sound',
  errorInRecording: 'Error voice recording',
  noVoiceAssistantAvailable: 'No voice assistant available at the moment',
  kTranslationLoadingAnimationText: 'Translating please wait...',
  errorPleaseSelectLanguage: 'Please select language',
  featureAvailableSoonInfo: 'This feature will be available soon',
  errorSelectVoiceAssistant: 'Please select voice assistant avatar',
  noTextForShare: 'No text found for share',
  noTextForCopy: 'No text found for copy',
  textCopiedToClipboard: 'Text copied to clipboard',
  femaleVoiceAssistantNotAvailable:
      'Female Voice assistant is not available, Playing from male voice assistant',
  maleVoiceAssistantNotAvailable:
      'Male Voice assistant is not available, Playing from female voice assistant',
  errorNoTextInClipboard: 'No text available in clipboard',
  s2sStreaming: 'S2S Streaming',
  connecting: 'Connecting...',
  somethingWentWrong: 'Something went wrong',
  tapAndHoldForRecording: 'Please tap and hold mic for recording',
  cannotPlayAudioAtTheMoment: 'Cannot play audio at the moment',
  responseNotReceived: 'Error: Response not received',
  translationNotPossible: 'translation not possible at the moment',
  bhashiniTitle: 'Bhashini',
  noAudioFoundToShare: 'No audio found to share',
  text: 'Text',
  converse: 'Converse',
  voice: 'Voice',
  video: 'Video',
  documents: 'Documents',
  images: 'Images',
  converseHintText: 'Press mic to begin conversation',
  textTranslateHintText: 'Start typing to begin',
  errorNoInternetTitle: 'No Internet Connection',
  errorNoInternetSubTitle: 'Please check your internet and try again',
  feedback: 'Feedback',
  writeReviewHere: 'Write your review here',
  submit: 'Submit',
  loading: 'Loading',
  errorGiveRating: 'Please give a rating',
  suggestedOutputTextASR:
      'If speech was not recognized properly, please edit it below:',
  suggestedOutputTextTranslate:
      'If translation was not correct, please edit it below:',
  realTimeResponse: 'Real Time Response',
  realTimeResponseInfo:
      'With this switched On, Transcriptions and Translations response can be obtained in real-time.',
  computeCallLoadingText: 'Hold on, we are generating the output',
  generalLanguages: 'General Languages',
  generalLanguagesBrief: 'These languages working perfectly',
  betaLanguages: 'Beta Languages',
  betaLanguagesBrief:
      'These languages are still in beta and are continuously improved for better results'
};
