import 'localization_keys.dart';

final Map<String, String> gom = {
  appName: 'भाशावर्स',
  selectAppLanguage: 'एपाची भास वेंचात',
  youCanAlwaysChange: 'तुमी हें जाय तेन्ना सेटिंग्सांत बदलूंक शकतात',
  searchLanguage: 'सोदपाची भास',
  continueText: 'फुडें व्हरात',
  next: 'फुडलें',
  skip: 'सोडून दियात',
  getStarted: 'सुरू करात',
  speechRecognition: 'उलोवप वळखप',
  automaticallyRecognizeAndConvert: 'आपसूक वळखून तुमचो आवाज टेक्सटांत बदलात',
  speechToSpeechTranslation: 'उलोवप ते उलोवपांतलो अणकार',
  translateYourVoiceInOneIndianLanguage:
      'तुमचो आवाज एका भारतीय भाशेंतल्यान दुसऱ्या भारतीय भाशेंत अणकारीत करात',
  languageTranslation: 'भाशेचो अणकार',
  translateSentencesFromOneIndianLanguageToAnother:
      'एका भारतीय भाशेंतल्यान दुसऱ्या भारतीय भाशेंत वाक्यां अणकारीत करात',
  bhashaverseChatBot: 'भाशावर्स चॅट बोट',
  selectVoiceAssistant: 'आवाज सहाय्यकाचो अवतार वेंचात',
  youWillHearTheTranslationText:
      'तुमी वेंचून काडिल्ल्या अवताराच्या आवाजांत तुमकां अणकार आयकूंक येतलो. सेटिंग्सांतल्यान तुमी जाय तेन्ना अवतार बदलूंक शकतात. ',
  male: 'दादलो',
  female: 'बायल',
  letsTranslate: 'अणकार करया ',
  appTheme: 'एप थीम',
  appInterfaceWillChange: 'एप इंटरफेस ते प्रमाण वेंचिल्ल्या प्रकारांत बदलतली.',
  light: 'लेव',
  dark: 'गडद',
  systemDefault: 'सिस्टम डिफोल्ट',
  appLanguage: 'एपाची भास',
  appInterfaceWillChangeInSelected: 'एप इंंटरफेस वेंचिल्ल्या भाशेंत बदलतली',
  voiceAssistant: 'आवाज सहाय्यक',
  transLiteration: 'लिप्यांतरण',
  transLiterationWillInitiateWord:
      'लिप्यांतरण तुमी टायप करता तेन्ना उतरां सुचयतलें',
  advanceSettings: 'प्रगत सेटिंगस',
  kTranslation: 'अणकार',
  kChat: 'चॅट',
  kSettings: 'सेटिंगस',
  kHomeLoadingAnimationText: 'रावात, आमी तुमचे खातीर गजाली जाग्यार घालतात',
  kTranslateSourceTitle: 'हाचो अणकार करात',
  kTranslateTargetTitle: 'हातूंत अणकार करात',
  kTranslationHintText: 'टायप करपाक सुरू करात वा मायक दामात',
  kListeningHintText: 'आयकता, आतां उलयात',
  kPaste: 'पेस्ट',
  kTranslate: 'अणकार करात',
  kReset: 'रिसेट',
  kErrorNoSourceText: 'पयलीं टेक्स्ट भितर घालात',
  kErrorSelectSourceAndTargetScreen: 'पयलींं स्त्रोत आनी लक्ष्य भास वेंचात ',
  errorMicPermission: 'आवाज रिकोर्ड करपाक मायकाची परवानगी जाय',
  errorInRecording: 'आवाज रिकोर्ड करपांत चूक',
  noVoiceAssistantAvailable: 'ह्या वेळार खंयचोच आवाज सहाय्यक उपलब्ध ना',
  kTranslationLoadingAnimationText: 'अणकार चल्ला, मातशें रावात',
  errorPleaseSelectLanguage: 'मातशी भास वेंचात',
  featureAvailableSoonInfo: 'ही सुवीधा रोखडीच उपलब्ध जातली',
  errorSelectVoiceAssistant: 'आवाज सहाय्यकाचो अवतार वेंचात',
  noTextForShare: 'शेर करपाक टेक्स्ट मेळूंक ना',
  noTextForCopy: 'कॉपी करपाक टेक्स्ट मेळूंक ना',
  textCopiedToClipboard: 'टेक्स्ट क्लिपबोर्डाचेर कॉपी केलां',
  femaleVoiceAssistantNotAvailable:
      'बायल आवाज सहाय्यक उपलब्ध ना, दादलो आवाज सहाय्यकाच्या आवाजांतल्यान आयकात',
  maleVoiceAssistantNotAvailable:
      'दादलो आवाज सहाय्यक उपलब्ध ना, बायल आवाज सहाय्यकाच्या आवाजांतल्यान आयकात',
  errorNoTextInClipboard: 'क्लिपबोर्डांत टेक्स्ट उपलब्ध ना',
  s2sStreaming: 'एस टू एस स्ट्रिमींग',
  connecting: 'कनेक्टींग',
  somethingWentWrong: 'कितें तरी चुकलें',
  tapAndHoldForRecording: 'रिकोर्डींगा खातीर टॅप करात आनी मायक होल्ड करात',
  cannotPlayAudioAtTheMoment: 'सद्या ऑडियो वाजोवंक शकना',
  responseNotReceived: 'एर्ररःजाप मेळूंक ना',
  translationNotPossible: 'सद्या अणकार शक्य ना',
  bhashiniTitle: 'भाशिणी',
};
