import 'localization_keys.dart';

final Map<String, String> gu = {
  appName: 'ભાષાવર્સ',
  selectAppLanguage: 'એપ્લીકેશનની ભાષા પસંદ કરો',
  youCanAlwaysChange: 'આપ સેટિંગમાંથી આને ગમે ત્યારે બદલી શકો છો.',
  searchLanguage: 'ભાષા શોધો',
  continueText: 'શરુ રાખો',
  next: 'આગળનું',
  skip: 'સ્કીપ કરો',
  getStarted: 'આરંભ કરો',
  speechRecognition: 'બોલી ઓળખ',
  automaticallyRecognizeAndConvert: 'આપનો અવાજ આપોઆપ ઓળખો અને ટેક્સ્ટમાં બદલો',
  speechToSpeechTranslation: 'વાણીથી વાણી અનુવાદ',
  translateYourVoiceInOneIndianLanguage:
      'આપના અવાજનો એક ભારતીય ભાષામાંથી બીજી ભારતીય ભાષામાં અનુવાદ કરો',
  languageTranslation: 'ભાષા અનુવાદ',
  translateSentencesFromOneIndianLanguageToAnother:
      'વાક્યોનો એક ભારતીય ભાષામાંથી બીજી ભારતીય ભાષામાં અનુવાદ કરો',
  bhashaverseChatBot: 'ભાષાવર્સ ચેટ બોક્સ',
  selectVoiceAssistant: 'ધ્વનિ સહાયક અવતાર પસંદ કરો',
  youWillHearTheTranslationText:
      'આપના દ્વારા પસંદ કરાયેલા અવતારના અવાજમાં આપને ભાષાંતર સંભળાશે. આપ ગમે ત્યારે સેટિંગમાંથી અવતાર બદલી શકશો.',
  male: 'પુરુષ',
  female: 'સ્ત્રી',
  letsTranslate: 'ચાલો અનુવાદ કરીએ',
  appTheme: 'એપ થીમ',
  appInterfaceWillChange: 'તે મુજબ એપ ઇન્ટરફેસ પસંદ કરેલા મોડમાં પરિવર્તિત થશે',
  light: 'ઝાંખું',
  dark: 'ઘાટું',
  systemDefault: 'સિસ્ટમ ડીફોલ્ટ',
  appLanguage: 'એપ ભાષા',
  appInterfaceWillChangeInSelected:
      'એપ ઇન્ટરફેસ પસંદ કરેલી ભાષામાં પરિવર્તિત થશે',
  voiceAssistant: 'ધ્વનિ સહાયક',
  transLiteration: 'લિપ્યંતરણ',
  transLiterationWillInitiateWord:
      'લિપ્યંતરણ આપના ટાઈપ કરતી સમયે શબ્દનું સુચન આરંભ કરશે',
  advanceSettings: 'એડવાન્સ સેટિંગ',
  kTranslation: 'અનુવાદ',
  kChat: 'સંવાદ',
  kSettings: 'સેટિંગ્સ',
  kHomeLoadingAnimationText: 'થોભો, અમે આપના માટે વસ્તુઓ ગોઠવી રહ્યા છીએ',
  kTranslateSourceTitle: 'માંથી અનુવાદ કરો',
  kTranslateTargetTitle: 'માં અનુવાદ કરો',
  kTranslationHintText: 'લખવું શરુ કરો અથવા શરુ કરવા માટે માઈક બટન દબાવો',
  kListeningHintText: 'સાંભળી રહ્યા છે, હવે બોલો',
  kPaste: 'પેસ્ટ કરો',
  kTranslate: 'અનુવાદ કરો',
  kReset: 'રીસેટ કરો',
  kErrorNoSourceText: 'કૃપયા ટેક્સ્ટ પહેલા દાખલ કરો',
  kErrorSelectSourceAndTargetScreen:
      'કૃપયા પહેલા સ્ત્રોત અને લક્ષ્ય ભાષા પસંદ કરો',
  errorMicPermission: 'અવાજ રેકોર્ડ કરવા માઈક પરવાનગી આવશ્યક છે',
  errorInRecording: 'ધ્વનિ રેકોર્ડીંગમાં ત્રુટી',
  noVoiceAssistantAvailable: 'આ સમયે કોઈ ધ્વનિ સહાયક ઉપલબ્ધ નથી',
  kTranslationLoadingAnimationText: 'અનુવાદ થઇ રહ્યો છે, કૃપયા પ્રતીક્ષા કરો',
  errorPleaseSelectLanguage: 'કૃપયા ભાષા પસંદ કરો',
  featureAvailableSoonInfo: 'આ સુવિધા જલદી ઉપલબ્ધ થશે',
  errorSelectVoiceAssistant: 'કૃપયા ધ્વનિ સહાયક અવતાર પસંદ કરો',
  noTextForShare: 'શેર કરવા માટે કોઈ ટેક્સ્ટ મળી નથી',
  noTextForCopy: 'કોપી કરવા માટે કોઈ ટેક્સ્ટ મળી નથી',
  textCopiedToClipboard: 'ટેક્સ્ટ કલીપબોર્ડ પર કોપી થઇ ગઈ છે',
  femaleVoiceAssistantNotAvailable:
      'સ્ત્રી ધ્વનિ સહાયક ઉપલબ્ધ નથી, પુરુષ ધ્વનિ સહાયક કાર્યરત છે',
  maleVoiceAssistantNotAvailable:
      'પુરુષ ધ્વનિ સહાયક ઉપલબ્ધ નથી, સ્ત્રી ધ્વનિ સહાયક કાર્યરત છે',
  errorNoTextInClipboard: 'કલીપબોર્ડમાં કોઈ ટેક્સ્ટ ઉપલબ્ધ નથી',
  s2sStreaming: 'એસ2એસ સ્ટ્રીમિંગ થઇ રહ્યું છે.',
  connecting: 'કનેક્ટ થઇ રહ્યું છે.',
  somethingWentWrong: 'કશીક ભૂલ થઇ છે ',
  tapAndHoldForRecording:
      'રેકોર્ડ કરવા માટે માઈક સામે ચપટી વગાડો અને પકડી રાખો ',
  cannotPlayAudioAtTheMoment: 'આ ક્ષણે ઓડિયો ચલાવી શકાશે નહીં ',
  responseNotReceived: 'ત્રુટી: કોઈ પ્રતિભાવ નથી મળ્યો',
  translationNotPossible: 'આ ક્ષણે અનુવાદ સંભવ નથી ',
  bhashiniTitle: 'ભાષીણી',
  bhashiniChatBot: 'ભાષીણી ચેટ બોટ ',
};
