import 'localization_keys.dart';

final Map<String, String> hi = {
  appName: 'भाषावर्स',
  selectAppLanguage: 'ऐप्लिकेशन की भाषा चुनें',
  youCanAlwaysChange: 'आप सेटिंग्स से इसे कभी भी बदल सकते हैं',
  searchLanguage: 'खोजने की भाषा',
  continueText: 'जारी रखें',
  next: 'अगला',
  skip: 'छोड़ दें',
  getStarted: 'आरंभ करें',
  speechRecognition: 'वाक् पहचान',
  automaticallyRecognizeAndConvert:
      'अपनी आवाज़ को स्वचालित रूप से पहचानें और टेक्स्ट में बदलें',
  speechToSpeechTranslation: 'संभाषण से संभाषण अनुवाद',
  translateYourVoiceInOneIndianLanguage:
      'अपनी आवाज़ का एक भारतीय भाषा से दूसरी भारतीय भाषा में अनुवाद करें',
  languageTranslation: 'भाषा का अनुवाद',
  translateSentencesFromOneIndianLanguageToAnother:
      'वाक्यों का एक भारतीय भाषा से दूसरी भाषा में अनुवाद करें',
  bhashaverseChatBot: 'भाषावर्स चैट बॉट',
  selectVoiceAssistant: 'ध्वनि सहायक अवतार चुनें',
  youWillHearTheTranslationText:
      'अपने चुने गए अवतार की आवाज में आपको अनुवाद सुनाई देगा। आप सेटिंग्स से कभी भी अवतार बदल सकते हैं।',
  male: 'पुरुष',
  female: 'स्त्री',
  letsTranslate: 'अनुवाद शूरू करें',
  appTheme: 'ऐप थीम',
  appInterfaceWillChange:
      'एप्लिकेशन इंटरफ़ेस तदनुसार चुने गए मोड में बदल जाएगा',
  light: 'हल्का',
  dark: 'गहरा',
  systemDefault: 'सिस्टम डिफ़ॉल्ट',
  appLanguage: 'ऐप भाषा',
  appInterfaceWillChangeInSelected:
      'ऐप इंटरफ़ेस चुनी गई ऐप भाषा में बदल जाएगा।',
  voiceAssistant: 'ध्वनि सहायक',
  transLiteration: 'लिप्यंतरण',
  transLiterationWillInitiateWord:
      'लिप्यंतरण आपके टाइप करते समय शब्द सुझाव आरंभ करेगा',
  advanceSettings: 'एडवांस सेटिंग',
  kTranslation: 'अनुवाद',
  kChat: 'बात करना',
  kSettings: 'सेटिंग्स',
  kHomeLoadingAnimationText: 'रुकें, हम आपके लिए चीज़ें सेट कर रहे हैं',
  kTranslateSourceTitle: 'से अनुवाद करें',
  kTranslateTargetTitle: 'में अनुवाद करें',
  kTranslationHintText: 'लिखना शुरू करें या शुरू करने के लिए माइक को दबाएं',
  kListeningHintText: 'सुन रहे हैं, अब आप बोलना शुरू करें',
  kPaste: 'पेस्ट',
  kTranslate: 'अनुवाद',
  kReset: 'रीसेट',
  kErrorNoSourceText: 'कृपया पहले टेक्स्ट दर्ज करें',
  kErrorSelectSourceAndTargetScreen: 'कृपया पहले स्रोत और लक्ष्य भाषा चुनें',
  errorMicPermission: 'ध्वनि रिकॉर्ड करने के लिए माइक अनुमति चाहिए',
  errorInRecording: 'ध्वनि रिकॉर्डिंग में त्रुटि',
  noVoiceAssistantAvailable: 'इस समय कोई ध्वनि सहायक उपलब्ध नहीं है',
  kTranslationLoadingAnimationText:
      'अनुवाद किया जा रहा है, कृपया प्रतीक्षा करें',
  errorPleaseSelectLanguage: 'कृपया भाषा चुनें',
  featureAvailableSoonInfo: 'यह सुविधा जल्द ही उपलब्ध होगी',
  errorSelectVoiceAssistant: 'कृपया ध्वनि सहायक अवतार चुनें',
  noTextForShare: 'साझा करने के लिए कोई टेक्स्ट नहीं मिला',
  noTextForCopy: 'कॉपी के लिए कोई टेक्स्ट नहीं मिला',
  textCopiedToClipboard: 'क्लिपबोर्ड पर टेक्स्ट कॉपी किया गया',
  femaleVoiceAssistantNotAvailable:
      'स्त्री ध्वनि सहायक उपलब्ध नहीं है, पुरुष ध्वनि सहायक से ध्वनि चल रही है',
  maleVoiceAssistantNotAvailable:
      'पुरुष ध्वनि सहायक उपलब्ध नहीं है, स्त्री ध्वनि सहायक से ध्वनि चल रही है',
  errorNoTextInClipboard: 'क्लिपबोर्ड में कोई टेक्स्ट उपलब्ध नहीं है',
  s2sStreaming: 'एस2एस स्ट्रीमिंग',
  connecting: 'कनेक्ट किया जा रहा है...',
  somethingWentWrong: 'कुछ गड़बड़ हो गया',
  tapAndHoldForRecording: 'रिकॉर्ड करने के लिए माइक को टैप करके पकड़े रहें',
  cannotPlayAudioAtTheMoment: 'इस समय ऑडियो नहीं चलाया जा सकता',
  responseNotReceived: 'त्रुटि - कोई प्रतिक्रिया नहीं मिली',
  translationNotPossible: 'इस समय अनुवाद संभव नहीं',
  bhashiniTitle: 'भाषिणी',
};
