import 'localization_keys.dart';

final Map<String, String> mai = {
  appName: 'भाषावर्स',
  selectAppLanguage: 'ऐप्लिकेशनक भाषा चुनु',
  youCanAlwaysChange: 'अहाँ सेटिंग्ससँ एकरा कखनो बदलि सकैत छी',
  searchLanguage: 'ढ़ूढ़बाक भाषा',
  continueText: 'चालू राखू',
  next: 'अगिला',
  skip: 'स्किप करू',
  getStarted: 'शुरू करू',
  speechRecognition: 'वाक् पहिचान',
  automaticallyRecognizeAndConvert:
      'अपन आवाजकेँ स्वचालित रूपसँ पहिचानू आ शब्दमे बदलू',
  speechToSpeechTranslation: 'वाक् सँ वाक् अनुवाद',
  translateYourVoiceInOneIndianLanguage:
      'अपन आवाजकेँ एकटा भारतीय भाषासँ दोसर भारतीय भाषामे अनुवाद करू',
  languageTranslation: 'भाषाक अनुवाद',
  translateSentencesFromOneIndianLanguageToAnother:
      'वाक्यसभकेँ एकटा भारतीय भाषासँ दोसर भारतीय भाषामे अनुवाद करू',
  bhashaverseChatBot: 'भाषावर्स चैट बॉट',
  selectVoiceAssistant: 'ध्वनि सहायकक अवतार चुनु',
  youWillHearTheTranslationText:
      'अपन चुनल अवतारक आवाजमे अहाँक अनुवाद सुनाय देत। अहाँ सेटिंग्ससँ कखनो अवतारकेँ बदलि सकैत छी।',
  male: 'पुरुष',
  female: 'महिला',
  letsTranslate: 'अनुवाद शूरू करू',
  appTheme: 'ऐप थीम',
  appInterfaceWillChange:
      'एप्लिकेशन इंटरफेस ओहि प्रकारसँ चयनित मोडमे बदलि जायत',
  light: 'हल्का',
  dark: 'गहिर',
  systemDefault: 'सिस्टम डिफॉल्ट',
  appLanguage: 'ऐप भाषा',
  appInterfaceWillChangeInSelected: 'ऐप इंटरफेस चयनित ऐप भाषामे बदलि जायत',
  voiceAssistant: 'ध्वनि सहायक',
  transLiteration: 'लिप्यंतरण',
  transLiterationWillInitiateWord:
      'लिप्यंतरण अहाँक टाइप करैत काल शब्द सुझाव आरम्भ करत',
  advanceSettings: 'एडवांस सेटिंग',
  kTranslation: 'अनुवाद',
  kChat: 'चैट',
  kSettings: 'सेटिंग्स',
  kHomeLoadingAnimationText: 'रुकू, हमसभ अहाँ लेल काज सेट कऽ रहल छी',
  kTranslateSourceTitle: 'सँ अनुवाद करू',
  kTranslateTargetTitle: 'मे अनुवाद करू',
  kTranslationHintText: 'टाइप केनाय शुरू करू आकि शुरू करबाक लेल माइककेँ दबाउ',
  kListeningHintText: 'सुनि रहल अछि, आब अहाँ बजनाय शुरू करू',
  kPaste: 'पेस्ट',
  kTranslate: 'अनुवाद',
  kReset: 'रीसेट',
  kErrorNoSourceText: 'कृप्या पहिने टेक्स्ट प्रविष्ट करू',
  kErrorSelectSourceAndTargetScreen: 'कृपया पहिने स्रोत आ लक्ष्य भाषा चुनु',
  errorMicPermission: 'ध्वनि रिकॉर्ड करबा लेल माइक के अनुमति चाही',
  errorInRecording: 'ध्वनि रिकॉर्डिंगमे त्रुटि',
  noVoiceAssistantAvailable: 'एहि काल कोनो ध्वनि सहायक उपलब्ध नहि अछि',
  kTranslationLoadingAnimationText: 'अनुवाद भऽ रहल अछि, कृप्या प्रतीक्षा करू',
  errorPleaseSelectLanguage: 'कृपया भाषा चुनु',
  featureAvailableSoonInfo: 'ई सुविधा तुरत उपलब्ध होयत',
  errorSelectVoiceAssistant: 'कृपया ध्वनि सहायकके अवतार चुनु',
  noTextForShare: 'साझा करबा लेल कोनो टेक्स्ट नहि भेटल',
  noTextForCopy: 'कॉपी करबा लेल कोनो टेक्स्ट नहि भेटल',
  textCopiedToClipboard: 'क्लिपबोर्ड पर टेक्स्ट कॉपी कयल गेल',
  femaleVoiceAssistantNotAvailable:
      'महिला ध्वनि सहायक उपलब्ध नहि अछि, पुरुष ध्वनि सहायकक ध्वनि चलि रहल अछि ',
  maleVoiceAssistantNotAvailable:
      'पुरुष ध्वनि सहायक उपलब्ध नहि अछि, महिला ध्वनि सहायकक ध्वनि चलि रहल अछि ',
  errorNoTextInClipboard: 'क्लिपबोर्डमे कोनो टेक्स्ट उपलब्ध नहि अछि',
  s2sStreaming: 'एस २ एस स्ट्रिमिंग',
  connecting: 'कनेक्ट भऽ रहल अछि...',
  somethingWentWrong: 'किछु दिक्कत भऽ गेल',
  tapAndHoldForRecording: 'रिकॉर्डिंग करबा लेल माइककेँ छूबि धेने रहू ',
  cannotPlayAudioAtTheMoment: 'अखन ऑडिओ नहि चलि सकैत अछि',
  responseNotReceived: 'त्रुटि : प्रतिक्रिया नहि भेटल',
  translationNotPossible: 'अखन अनुवाद सम्भव नहि',
  bhashiniTitle: 'भाषिणी',
  bhashiniChatBot: 'भाषिणी चैट बॉट',
};
