import 'localization_keys.dart';

final Map<String, String> mni = {
  appName: 'ꯚꯥꯁꯥꯕꯔꯁ',
  selectAppLanguage: 'ꯑꯦꯞꯀꯤ ꯂꯣꯟ ꯈꯟꯕꯤꯌꯨ',
  youCanAlwaysChange: 'ꯑꯗꯣꯝꯅ ꯃꯁꯤꯕꯨ ꯁꯦꯇꯤꯡꯁꯇꯒꯤ ꯃꯇꯝ ꯑꯃꯍꯦꯛꯇꯗ ꯑꯣꯟꯊꯣꯛꯄꯤꯕ ꯌꯥꯒꯅꯤ',
  searchLanguage: 'ꯂꯣꯟ ꯊꯤꯕꯤꯌꯨ',
  continueText: 'ꯃꯈꯥ ꯆꯠꯊꯧ',
  next: 'ꯃꯊꯪ',
  skip: 'ꯀꯥꯟꯊꯣꯛꯎ',
  getStarted: 'ꯍꯧꯔꯁꯤ',
  speechRecognition: 'ꯁ꯭ꯄꯤꯆ ꯔꯤꯀꯣꯒꯅꯤꯁꯟ',
  automaticallyRecognizeAndConvert:
      'ꯑꯗꯣꯝꯒꯤ ꯈꯣꯟꯖꯦꯜ ꯑꯗꯨ ꯃꯇꯣꯝꯇ ꯈꯪꯗꯣꯛꯂꯗꯨꯅ ꯇꯦꯛꯁꯠꯇ ꯑꯣꯟꯊꯣꯛꯄꯤꯌꯨ',
  speechToSpeechTranslation: 'ꯈꯣꯜꯍꯥꯏ ꯑꯃꯗꯒꯤ ꯈꯣꯜꯍꯥꯏ ꯑꯃꯗ ꯂꯣꯟ ꯍꯟꯗꯣꯛꯄ',
  translateYourVoiceInOneIndianLanguage:
      'ꯑꯗꯣꯝꯒꯤ ꯈꯣꯟꯖꯦꯜ ꯑꯗꯨ ꯚꯥꯔꯠꯀꯤ ꯂꯣꯟ ꯑꯃꯗꯒꯤ ꯑꯃꯗ ꯍꯟꯗꯣꯛꯄꯤꯌꯨ',
  languageTranslation: 'ꯂꯣꯟ ꯍꯟꯗꯣꯛꯄ',
  translateSentencesFromOneIndianLanguageToAnother:
      'ꯋꯥꯍꯩ ꯄꯔꯦꯡꯁꯤꯡꯕꯨ ꯚꯥꯔꯠꯀꯤ ꯂꯣꯟ ꯑꯃꯗꯒꯤ ꯑꯃꯗ ꯍꯟꯗꯣꯛꯄꯤꯌꯨ',
  bhashaverseChatBot: 'ꯚꯥꯔꯠꯕꯔꯁ ꯆꯥꯠ ꯕꯣꯠ',
  selectVoiceAssistant: 'ꯚꯣꯏꯁ ꯑꯦꯁꯤꯁꯇꯦꯟꯠ ꯑꯕꯇꯥꯔ ꯈꯟꯕꯤꯌꯨ',
  youWillHearTheTranslationText:
      'ꯑꯗꯣꯝꯅ ꯈꯟꯈ꯭ꯔꯕ ꯑꯕꯇꯥꯔ ꯑꯗꯨꯒꯤ ꯈꯣꯟꯖꯦꯜꯗ ꯍꯟꯗꯣꯛꯂꯤꯕ ꯑꯗꯨ ꯇꯥꯕꯤꯒꯅꯤ꯫ ꯑꯗꯣꯝꯅ ꯁꯦꯇꯤꯡꯁꯇꯒꯤ ꯃꯇꯝ ꯑꯃꯍꯦꯛꯇꯗ ꯑꯕꯇꯥꯔ ꯑꯣꯟꯊꯣꯛꯄ ꯌꯥꯒꯅꯤ ',
  male: 'ꯅꯨꯄꯥ',
  female: 'ꯅꯨꯄꯤ',
  letsTranslate: 'ꯂꯣꯟ ꯍꯟꯗꯣꯛꯂꯁꯤ',
  appTheme: 'ꯑꯦꯞꯀꯤ ꯊꯤꯝ',
  appInterfaceWillChange: 'ꯈꯜꯂꯕ ꯃꯣꯗ ꯑꯗꯨꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯑꯦꯞ ꯏꯟꯇꯔꯐꯦꯁ ꯍꯣꯡꯒꯅꯤ',
  light: 'ꯑꯉꯥꯟꯕ',
  dark: 'ꯑꯃꯝꯕ',
  systemDefault: 'ꯁꯤꯁꯇꯦꯝ ꯗꯤꯐꯣꯜꯠ',
  appLanguage: 'ꯑꯦꯞꯀꯤ ꯂꯣꯟ',
  appInterfaceWillChangeInSelected: 'ꯈꯜꯂꯕ ꯑꯦꯞꯀꯤ ꯂꯣꯟ ꯑꯗꯨꯗ ꯑꯦꯞ ꯏꯟꯇꯔꯐꯦꯁ ꯍꯣꯡꯒꯅꯤ',
  voiceAssistant: 'ꯚꯣꯏꯁ ꯑꯦꯁꯤꯁꯇꯦꯟꯠ',
  transLiteration: 'ꯇ꯭ꯔꯥꯟꯁꯂꯤꯇꯔꯦꯁꯟ / ꯃꯌꯦꯛ ꯍꯟꯗꯣꯛꯄ',
  transLiterationWillInitiateWord:
      'ꯑꯗꯣꯝꯅ ꯇꯥꯏꯞ ꯇꯧꯕ ꯃꯇꯝꯗ ꯇ꯭ꯔꯥꯟꯁꯂꯤꯇꯔꯦꯁꯟꯅ ꯋꯔꯗ ꯁꯖꯦꯁꯟꯁ ꯍꯧꯗꯣꯛꯀꯅꯤ',
  advanceSettings: 'ꯑꯦꯗꯚꯥꯟꯁ ꯁꯦꯇꯤꯡꯁ',
  kTranslation: 'ꯂꯣꯟ ꯍꯟꯗꯣꯛꯄ',
  kChat: 'ꯆꯥꯠ',
  kSettings: 'ꯁꯦꯇꯤꯡꯁ',
  kHomeLoadingAnimationText: 'ꯉꯥꯏꯍꯥꯛ ꯉꯥꯏꯕꯤꯌꯨ, ꯑꯗꯣꯝꯒꯤꯗꯃꯛ ꯁꯦꯠꯑꯞ ꯇꯧꯖꯔꯤ',
  kTranslateSourceTitle: 'ꯗꯒꯤ ꯍꯟꯗꯣꯛꯄꯤꯌꯨ',
  kTranslateTargetTitle: 'ꯗ ꯍꯟꯗꯣꯛꯄꯤꯌꯨ',
  kTranslationHintText: 'ꯍꯧꯅꯅꯕ ꯇꯥꯏꯞ ꯇꯧꯕ ꯍꯧꯕꯤꯌꯨ ꯅꯠꯇ꯭ꯔꯒ ꯃꯥꯏꯛꯇ ꯟꯝꯕꯤꯌꯨ',
  kListeningHintText: 'ꯇꯥꯖꯔꯤ, ꯍꯧꯖꯤꯛ ꯍꯥꯏꯕꯤꯔꯛꯑꯣ / ꯍꯥꯏꯕꯤꯔꯛꯂꯣ, ꯇꯥꯖꯔꯤ',
  kPaste: 'ꯄꯦꯁꯠ',
  kTranslate: 'ꯂꯣꯟ ꯍꯟꯗꯣꯛꯎ',
  kReset: 'ꯔꯤꯁꯦꯠ',
  kErrorNoSourceText: 'ꯆꯥꯟꯕꯤꯗꯨꯅ ꯇꯦꯛꯁꯠ ꯍꯥꯟꯅ ꯃꯦꯟꯕꯤꯌꯨ',
  kErrorSelectSourceAndTargetScreen:
      'ꯆꯥꯟꯕꯤꯗꯨꯅ ꯁꯣꯔꯁ ꯑꯃꯗꯤ ꯇꯥꯔꯒꯦꯠ ꯂꯦꯡꯒꯨꯑꯦꯖ ꯍꯥꯟꯅ ꯈꯟꯕꯤꯌꯨ',
  errorMicPermission: 'ꯃꯈꯣꯜ ꯔꯦꯀꯣꯔꯗ ꯇꯧꯕ ꯃꯇꯝꯗ ꯃꯥꯏꯛꯀꯤ ꯑꯌꯥꯕ ꯃꯊꯧ ꯇꯥꯏ',
  errorInRecording: 'ꯈꯣꯟꯖꯦꯜ ꯔꯦꯀꯣꯔꯗ ꯇꯧꯕ ꯌꯥꯗ꯭ꯔꯦ',
  noVoiceAssistantAvailable: 'ꯄꯨꯡꯐꯝ ꯑꯁꯤꯗ ꯚꯣꯏꯁ ꯑꯦꯁꯤꯁꯇꯦꯟꯠ ꯑꯃꯠꯇ ꯂꯩꯇꯦ',
  kTranslationLoadingAnimationText: 'ꯂꯣꯟ ꯍꯟꯗꯣꯛꯂꯤ, ꯆꯥꯟꯕꯤꯗꯨꯅ ꯉꯥꯏꯕꯤꯌꯨ',
  errorPleaseSelectLanguage: 'ꯆꯥꯟꯕꯤꯗꯨꯅ ꯂꯣꯟ ꯈꯟꯕꯤꯌꯨ',
  featureAvailableSoonInfo: 'ꯃꯁꯤꯒꯤ ꯐꯤꯆꯔ ꯑꯁꯤ ꯌꯥꯝꯅ ꯊꯨꯅ ꯐꯪꯂꯒꯅꯤ',
  errorSelectVoiceAssistant: 'ꯆꯥꯟꯕꯤꯗꯨꯅ ꯚꯣꯏꯁ ꯑꯦꯁꯤꯁꯇꯦꯟꯠ ꯑꯕꯇꯥꯔ ꯈꯟꯕꯤꯌꯨ',
  noTextForShare: 'ꯁꯤꯌꯥꯔ ꯇꯧꯅꯅꯕ ꯇꯦꯛꯁꯠ ꯑꯃꯠꯇ ꯐꯪꯗ꯭ꯔꯦ',
  noTextForCopy: 'ꯀꯣꯄꯤ ꯇꯧꯅꯅꯕ ꯇꯦꯛꯁꯠ ꯑꯃꯠꯇ ꯐꯪꯗ꯭ꯔꯦ',
  textCopiedToClipboard: 'ꯀ꯭ꯂꯤꯞꯕꯣꯔꯗꯇ ꯇꯦꯛꯁꯠ ꯀꯣꯄꯤ ꯇꯧꯈ꯭ꯔꯦ',
  femaleVoiceAssistantNotAvailable:
      'ꯅꯨꯄꯤꯒꯤ ꯚꯣꯏꯁ ꯑꯦꯁꯤꯁꯇꯦꯟꯠ ꯂꯩꯇꯦ, ꯅꯨꯄꯥꯒꯤ ꯚꯣꯏꯁ ꯑꯦꯁꯤꯁꯇꯦꯟꯠꯇꯒꯤ ꯊꯥꯖꯔꯤ',
  maleVoiceAssistantNotAvailable:
      'ꯅꯨꯄꯥꯒꯤ ꯚꯣꯏꯁ ꯑꯦꯁꯤꯁꯇꯦꯟꯠ ꯂꯩꯇꯦ, ꯅꯨꯄꯤꯒꯤ ꯚꯣꯏꯁ ꯑꯦꯁꯤꯁꯇꯦꯟꯠꯇꯒꯤ ꯊꯥꯖꯔꯤ',
  errorNoTextInClipboard: 'ꯀ꯭ꯂꯤꯞꯕꯣꯔꯗꯇ ꯇꯦꯛꯁꯠ ꯑꯃꯠꯇ ꯌꯥꯎꯗꯦ',
  s2sStreaming: 'ꯑꯦꯁ ꯇꯨ ꯑꯦꯁ ꯁ꯭ꯇ꯭ꯔꯤꯃꯤꯡ',
  connecting: 'ꯀꯅꯦꯛ ꯇꯩꯔꯤ...',
  somethingWentWrong: 'ꯀꯔꯤꯒꯨꯝꯕ ꯑꯁꯣꯏꯕ ꯑꯃ ꯂꯩꯔꯦ',
  tapAndHoldForRecording: 'ꯆꯥꯟꯕꯤꯗꯨꯅ ꯔꯦꯀꯣꯔꯗꯤꯡ ꯇꯩꯅꯕꯒꯤꯗꯃꯛ ꯃꯥꯏꯛ ꯑꯗꯨ ꯅꯝꯗꯨꯅ ꯊꯝꯕꯤꯌꯨ',
  cannotPlayAudioAtTheMoment: 'ꯃꯤꯀꯨꯞ ꯑꯁꯤꯗ ꯑꯣꯗꯤꯑꯣ ꯊꯥꯕ ꯌꯥꯗ꯭ꯔꯦ',
  responseNotReceived: 'ꯑꯦꯔꯔ: ꯔꯦꯁꯄꯣꯟꯁ ꯐꯪꯗ꯭ꯔꯦ',
  translationNotPossible: 'ꯃꯤꯀꯨꯞ ꯑꯁꯤꯗ ꯂꯣꯟ ꯍꯟꯗꯣꯛꯄ ꯌꯥꯗ꯭ꯔꯦ',
  bhashiniTitle: 'ꯚꯥꯁꯤꯅꯤ',
};
