import 'localization_keys.dart';

final Map<String, String> pa = {
  appName: 'ਭਾਸ਼ਾਵਰਸ ',
  selectAppLanguage: 'ਐਪ ਦੀ ਭਾਸ਼ਾ ਚੁਣੋ ',
  youCanAlwaysChange: 'ਤੁਸੀਂ ਕਦੋਂ ਵੀ ਇਸ ਨੂੰ ਸੈੱਟਿੰਗਸ ਤੋਂ ਬਦਲ ਸਕਦੇ ਹੋ',
  searchLanguage: 'ਭਾਸ਼ਾ ਖੋਜੋ ',
  continueText: 'ਜਾਰੀ ਰੱਖੋ ',
  next: 'ਅਗਲਾ ',
  skip: 'ਸਕਿਪ ਕਰੋ ',
  getStarted: 'ਸ਼ੁਰੂ ਕਰੋ ',
  speechRecognition: 'ਬੋਲੀ ਦੀ ਪਛਾਣ ',
  automaticallyRecognizeAndConvert:
      'ਆਪਣੀ ਆਵਾਜ਼ ਨੂੰ ਸਵੈਚਲਿਤ ਰੂਪ ਵਿੱਚ ਪਛਾਣੋ ਅਤੇ ਟੈਕਸਟ ਵਿੱਚ ਬਦਲੋ',
  speechToSpeechTranslation: 'ਕਥਨ ਤੋਂ ਕਥਨ ਅਨੁਵਾਦ ',
  translateYourVoiceInOneIndianLanguage:
      'ਆਪਣੀ ਆਵਾਜ਼ ਨੂੰ ਇੱਕ ਭਾਰਤੀ ਭਾਸ਼ਾ ਤੋਂ ਦੂਸਰੀ ਵਿੱਚ ਅਨੁਵਾਦ ਕਰੋ  ',
  languageTranslation: 'ਭਾਸ਼ਾ ਦਾ ਅਨੁਵਾਦ ',
  translateSentencesFromOneIndianLanguageToAnother:
      'ਵਾਕਾਂ ਨੂੰ ਇੱਕ ਭਾਰਤੀ ਭਾਸ਼ਾ ਤੋਂ ਦੂਸਰੀ ਵਿੱਚ ਅਨੁਵਾਦ ਕਰੋ   ',
  bhashaverseChatBot: 'ਭਾਸ਼ਾਵਰਸ ਚੈਟ ਬੋਟ',
  selectVoiceAssistant: 'ਆਵਾਜ਼ ਸਹਾਇਕ ਅਵਤਾਰ ਚੁਣੋ ',
  youWillHearTheTranslationText:
      'ਤੁਸੀਂ ਆਪਣੇ ਦੁਆਰਾ ਚੁਣੇ ਗਏ ਅਵਤਾਰ ਦੀ ਆਵਾਜ਼ ਵਿੱਚ ਅਨੁਵਾਦ ਸੁਣੋਗੇ। ਤੁਸੀਂ ਹਮੇਸ਼ਾ ਅਵਤਾਰ ਨੂੰ ਸੈਟਿੰਗ ਤੋਂ ਬਦਲ ਸਕਦੇ ਹੋ',
  male: 'ਮਰਦ ',
  female: 'ਔਰਤ ',
  letsTranslate: 'ਅਨੁਵਾਦ ਸ਼ੁਰੂ ਕਰੀਏ। ',
  appTheme: 'ਐਪ ਥੀਮ ',
  appInterfaceWillChange: 'ਐਪ ਦਾ ਇੰਟਰਫੇਸ ਚੁਣੇ ਗਏ ਮੋਡ ਅਨੁਸਾਰ ਉਸ ਵਿੱਚ ਬਦਲ ਜਾਵੇਗਾ',
  light: 'ਫਿੱਕਾ ',
  dark: 'ਗੂੜ੍ਹਾ ',
  systemDefault: 'ਸਿਸਟਮ ਡਿਫੌਲਟ',
  appLanguage: 'ਐਪ ਭਾਸ਼ਾ ',
  appInterfaceWillChangeInSelected:
      'ਐਪ ਦਾ ਇੰਟਰਫੇਸ ਚੁਣੀ ਹੋਈ ਐਪ ਭਾਸ਼ਾ ਵਿੱਚ ਬਦਲ ਜਾਵੇਗਾ',
  voiceAssistant: 'ਆਵਾਜ਼ ਸਹਾਇਕ ',
  transLiteration: 'ਲਿਪੀਅੰਤਰਨ',
  transLiterationWillInitiateWord:
      'ਲਿਪੀਅੰਤਰਨ ਤੁਹਾਡੇ ਟਾਈਪ ਕਰਦੇ ਹੋਏ ਸ਼ਬਦਾਂ ਦਾ ਸੁਝਾਵ ਦੇਣਾ ਸ਼ੁਰੂ ਕਰ ਦੇਵੇਗਾ। ',
  advanceSettings: 'ਉੱਨਤ ਸੈਟਿੰਗਾਂ',
  kTranslation: 'ਅਨੁਵਾਦ',
  kChat: 'ਚੈਟ ',
  kSettings: 'ਸੈਟਿੰਗਾਂ',
  kHomeLoadingAnimationText: 'ਰੁਕੋ, ਅਸੀਂ ਤੁਹਾਡੇ ਲਈ ਚੀਜ਼ਾਂ ਤੈਅ ਕਰ ਰਹੇ ਹਾਂ। ',
  kTranslateSourceTitle: 'ਤੋਂ ਅਨੁਵਾਦ ',
  kTranslateTargetTitle: 'ਵਿੱਚ ਅਨੁਵਾਦ ',
  kTranslationHintText: 'ਲਿਖਣਾ ਸ਼ੁਰੂ ਕਰੋ ਜਾਂ ਮਾਈਕ ਨੂੰ ਦਬਾਓ  ',
  kListeningHintText: 'ਸੁਣ ਰਹੇ ਹਾਂ, ਹੁਣ ਬੋਲੋ ',
  kPaste: 'ਪੇਸਟ ',
  kTranslate: 'ਅਨੁਵਾਦ',
  kReset: 'ਰੀਸੈਟ ',
  kErrorNoSourceText: 'ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਟੈਕਸਟ ਦਰਜ ਕਰੋ ',
  kErrorSelectSourceAndTargetScreen:
      'ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਸਰੋਤ ਅਤੇ ਨਿਸ਼ਾਨਾ ਭਾਸ਼ਾ ਚੁਣੋ',
  errorMicPermission: 'ਆਵਾਜ਼ ਰਿਕਾਰਡ ਕਰਨ ਲਈ ਮਾਈਕ ਦੀ ਆਗਿਆ ਚਾਹੀਦੀ ਹੈ ',
  errorInRecording: 'ਅਵਾਜ਼ ਰਿਕਾਰਡਿੰਗ ਵਿੱਚ ਗੜਬੜ',
  noVoiceAssistantAvailable: 'ਇਸ ਸਮੇਂ ਕੋਈ ਆਵਾਜ਼ ਸਹਾਇਕ ਉਪਲਬਧ ਨਹੀਂ ਹੈ ',
  kTranslationLoadingAnimationText: 'ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ, ਕਿਰਪਾ ਕਰਕੇ ਇੰਤਜ਼ਾਰ ਕਰੋ ',
  errorPleaseSelectLanguage: 'ਕਿਰਪਾ ਕਰਕੇ ਭਾਸ਼ਾ ਚੁਣੋ ',
  featureAvailableSoonInfo: 'ਇਹ ਸੁਵਿਧਾ ਜਲਦ ਹੀ ਉਪਲਬਧ ਹੋਵੇਗੀ ',
  errorSelectVoiceAssistant: 'ਕਿਰਪਾ ਕਰਕੇ ਆਵਾਜ਼ ਸਹਾਇਕ ਅਵਤਾਰ ਚੁਣੋ ',
  noTextForShare: 'ਸਾਂਝਾ ਕਰਨ ਲਈ ਕੋਈ ਟੈਕਸਟ ਨਹੀਂ ਮਿਲਿਆ ',
  noTextForCopy: 'ਕਾਪੀ ਕਰਨ ਲਈ ਕੋਈ ਟੈਕਸਟ ਨਹੀਂ ਮਿਲਿਆ ',
  textCopiedToClipboard: 'ਕਲਿਪਬੋਰਡ ਤੇ ਟੈਕਸਟ ਕਾਪੀ ਹੋ ਗਿਆ ਹੈ ',
  femaleVoiceAssistantNotAvailable:
      'ਔਰਤ ਆਵਾਜ਼ ਸਹਾਇਕ ਉਪਲਬਧ ਨਹੀਂ ਹੈ, ਮਰਦ ਆਵਾਜ਼ ਸਹਾਇਕ ਤੋਂ ਚਲਾਇਆ ਜਾ ਰਿਹਾ ਹੈ',
  maleVoiceAssistantNotAvailable:
      ' ਮਰਦ ਆਵਾਜ਼ ਸਹਾਇਕ ਉਪਲਬਧ ਨਹੀਂ ਹੈ, ਔਰਤ ਆਵਾਜ਼ ਸਹਾਇਕ ਤੋਂ ਚਲਾਇਆ ਜਾ ਰਿਹਾ ਹੈ',
  errorNoTextInClipboard: 'ਕਲਿਪਬੋਰਡ ਤੇ ਕੋਈ ਟੈਕਸਟ ਉਪਲਬਧ ਨਹੀਂ ਹੈ ',
  s2sStreaming: 'ਐਸ 2 ਐਸ ਸਟ੍ਰੀਮਿੰਗ ',
  connecting: 'ਜੁੜ ਰਿਹਾ ਹੈ.. ',
  somethingWentWrong: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
  tapAndHoldForRecording:
      'ਕਿਰਪਾ ਕਰਕੇ ਰਿਕਾਰਡਿੰਗ ਲਈ ਮਾਈਕ ਨੂੰ ਟੈਪ ਕਰੋ ਅਤੇ ਹੋਲਡ ਕਰੋ',
  cannotPlayAudioAtTheMoment: 'ਇਸ ਸਮੇਂ ਔਡੀਓ ਨਹੀਂ ਚਲਾਇਆ ਜਾ ਸਕਦਾ',
  responseNotReceived: 'ਤਰੁੱਟੀ: ਜਵਾਬ ਨਹੀਂ ਮਿਲਿਆ ',
  translationNotPossible: 'ਇਸ ਸਮੇਂ ਅਨੁਵਾਦ ਸੰਭਵ ਨਹੀਂ ਹੈ',
  bhashiniTitle: 'ਭਾਸ਼ਿਨੀ',
};
