import 'localization_keys.dart';

final Map<String, String> sa = {
  appName: 'भाषावर्स्',
  selectAppLanguage: 'अप्लिकेशन्-भाषां चिनोतु',
  youCanAlwaysChange:
      'त्वम् एतत् सेट्टिङ्ग्स् इत्यस्मात् कदापि परिवर्तितुम् अर्हसि',
  searchLanguage: 'भाषाशोधः',
  continueText: 'प्रवर्तताम्',
  next: 'अग्रे',
  skip: 'उपेक्षताम्',
  getStarted: 'प्रारभताम्',
  speechRecognition: 'वाचः अभिज्ञानम्',
  automaticallyRecognizeAndConvert:
      'स्वयमेव तव ध्वनिम् अभिज्ञाय लिपिरूपेण परिवर्तयतु।',
  speechToSpeechTranslation: 'सम्भाषणतः सम्भाषाणस्य अनुवादः',
  translateYourVoiceInOneIndianLanguage:
      'एकस्याः भारतीयभाषायाः अपरस्यां भारतीयभाषायां तव ध्वनिम् अनुवदतु।',
  languageTranslation: 'भाषायाः अनुवादः',
  translateSentencesFromOneIndianLanguageToAnother:
      'एकस्याः भारतीयभाषायाः अपरस्यां भारतीयभाषायां वाक्यानि अनुवदतु।',
  bhashaverseChatBot: 'भाषावर्स् चाट्बाट्',
  selectVoiceAssistant: 'ध्वनिसहायकम् अवतारं चिनोतु।',
  youWillHearTheTranslationText:
      'त्वं चितस्य अवतारस्य ध्वनौ अनुवादं शृणोषि। त्वम् अवतारं सेट्टिङ्ग्स् इत्यस्मात् कदापि परिवर्तितुम् अर्हसि',
  male: 'पुरुषः',
  female: 'स्त्री',
  letsTranslate: 'अनुवादं प्रारभामहे',
  appTheme: 'आप् थीम्',
  appInterfaceWillChange: 'आप् इन्टर्फ़ेस् चयितया रीत्या परिवर्तयति',
  light: 'शुक्लम्',
  dark: 'कृष्णम्',
  systemDefault: 'सिस्टम् पूर्वनियुक्तम्',
  appLanguage: 'आप् भाषा',
  appInterfaceWillChangeInSelected:
      'आप् इन्टर्फ़ेस् चयितायाम् आप्-भाषायां परिवर्तते',
  voiceAssistant: 'ध्वनिसहायकः',
  transLiteration: 'लिप्यन्तरः',
  transLiterationWillInitiateWord:
      'लिप्यन्तरः टैप् कुर्वतः तव शब्दसूचनाम् आरभते',
  advanceSettings: 'अड्वान्स्ड् सेट्टिङ्ग्स्',
  kTranslation: 'अनुवादः',
  kChat: 'सम्भाषणम्',
  kSettings: 'सेट्टिङ्ग्स्',
  kHomeLoadingAnimationText: 'निरीक्षताम्, भवत्कृते वयं साधनानि साधयन्तः स्मः',
  kTranslateSourceTitle: 'अस्मात् अनुवदतु',
  kTranslateTargetTitle: 'अस्मिन् अनुवदतु',
  kTranslationHintText: 'टैप् आरभताम् अथवा प्रारब्द्धुं मैक् नुदतु',
  kListeningHintText: 'श्रूयते, वाचं वदतु',
  kPaste: 'लेपयतु',
  kTranslate: 'अनुवदतु',
  kReset: 'यथास्थिति',
  kErrorNoSourceText: 'कृपया प्रथमं तावत् टेक्स्ट् अङ्कयतु',
  kErrorSelectSourceAndTargetScreen:
      'कृपया प्रथमं तावत् मूलभाषाम् उद्दिष्टभाषां च चिनोतु',
  errorMicPermission: 'ध्वनिमुद्रणकरणे मैक् अनुमतिः आवश्यकी',
  errorInRecording: 'ध्वनिमुद्रणे दोषः',
  noVoiceAssistantAvailable: 'सद्यः ध्वनिसहायकः न लभ्यते',
  kTranslationLoadingAnimationText: 'अनुवादः आरब्धः निरीक्षताम्',
  errorPleaseSelectLanguage: 'कृपया भाषां चिनोतु',
  featureAvailableSoonInfo: 'विशेषः सः अचिरेण लभ्यते',
  errorSelectVoiceAssistant: 'कृपया ध्वनिसहायकम् अवतारं चिनोतु',
  noTextForShare: 'शेर् करणे किमपि टेक्स्ट् नोपलभ्यते',
  noTextForCopy: 'कापि करणे किमपि टेक्स्ट् नोपलभ्यते',
  textCopiedToClipboard: 'क्लिप्बोर्ड् इत्यस्मिन् टेक्स्ट् प्रतिकृतम्',
  femaleVoiceAssistantNotAvailable:
      'स्त्रीरूपः ध्वनिसहायकः नोपलभ्यते, पुरुषरूपात् ध्वनिसहायकात् चाल्यते',
  maleVoiceAssistantNotAvailable:
      'पुरुषरूपः ध्वनिसहायकः नोपलभ्यते, स्त्रीरूपात् ध्वनिसहायकात् चाल्यते',
  errorNoTextInClipboard: 'क्लिप्बोर्ड् इत्यस्मिन् टेक्स्ट् किमपि नोपलोभ्यते',
  s2sStreaming: 'एस् २ एस् स्ट्रीमिङ्ग्',
  connecting: 'सन्दधाति...',
  somethingWentWrong: 'किमपि अयुक्तम् सञ्जातम्',
  tapAndHoldForRecording: 'कृपया, मुद्राङ्कनं कर्तुं मैक् नुत्वा धीयताम् ',
  cannotPlayAudioAtTheMoment: 'सद्यः ध्वनिं विधातुं न शक्नुमः',
  responseNotReceived: 'दोषः - प्रतिस्पन्दनं न लभ्यते',
  translationNotPossible: 'सद्यः अनुवादः न साध्यः',
  bhashiniTitle: 'भाषिणी',
};
