import 'localization_keys.dart';

final Map<String, String> sat = {
  appName: 'ᱵᱷᱟᱥᱟᱵᱚᱨᱥᱚ',
  selectAppLanguage: 'ᱮᱯ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
  youCanAlwaysChange: 'ᱟᱢ ᱱᱟᱶᱟ ᱥᱟᱨᱟ ᱵᱮᱲᱟᱜᱮ ᱥᱮᱴᱤᱝ ᱠᱷᱚᱱᱮᱢ ᱵᱚᱫᱚᱞ ᱫᱟᱲᱮᱭᱟᱜᱼᱟ',
  searchLanguage: 'ᱯᱟᱹᱨᱥᱤ ᱥᱮᱸᱫᱽᱨᱟ',
  continueText: 'ᱞᱮᱛᱟᱲ',
  next: 'ᱱᱤᱭᱟᱹ ᱛᱟᱭᱱᱚᱢ',
  skip: 'ᱮᱲᱟᱣ',
  getStarted: 'ᱮᱛᱚᱦᱚᱵᱽ ᱢᱮ',
  speechRecognition: 'ᱨᱚᱲ ᱩᱨᱩᱢ',
  automaticallyRecognizeAndConvert:
      'ᱟᱡᱟᱡᱛᱮ ᱩᱨᱩᱢ ᱟᱨ ᱟᱢᱟᱜ ᱟᱲᱟᱝ ᱚᱞᱨᱚᱲ ᱠᱷᱚᱱ ᱨᱚᱲ ᱛᱚᱨᱡᱚᱢᱟ ᱨᱮ ᱯᱷᱮᱨᱟᱣ',
  speechToSpeechTranslation: 'ᱨᱚᱲ ᱠᱷᱚᱱ ᱨᱚᱲ ᱛᱚᱨᱡᱚᱢᱟᱭ',
  translateYourVoiceInOneIndianLanguage:
      'ᱟᱢᱟᱜ ᱟᱲᱟᱝ ᱢᱤᱫ ᱵᱷᱟᱨᱚᱛᱤᱭᱟᱹ ᱯᱟᱹᱨᱥᱤ ᱠᱷᱚᱱ ᱮᱴᱟᱜ ᱵᱷᱟᱨᱚᱛᱤᱭᱟᱹ ᱯᱟᱹᱨᱥᱤᱨᱮ ᱛᱚᱨᱡᱚᱢᱟ',
  languageTranslation: 'ᱯᱟᱹᱨᱥᱤ ᱛᱚᱨᱡᱚᱢᱟᱭ',
  translateSentencesFromOneIndianLanguageToAnother:
      'ᱟᱹᱭᱟᱹᱛ ᱢᱤᱫ ᱵᱷᱟᱨᱚᱛᱤᱭᱟᱹ ᱯᱟᱹᱨᱥᱤ ᱠᱷᱚᱱ ᱮᱴᱟᱜ ᱯᱟᱹᱨᱥᱤᱨᱮ ᱛᱚᱨᱡᱚᱢᱟ',
  bhashaverseChatBot: 'ᱵᱷᱟᱥᱟᱵᱚᱨᱥᱚ ᱪᱮᱴ ᱵᱚᱴ',
  selectVoiceAssistant: 'ᱟᱲᱟᱝ ᱥᱚᱦᱮᱫᱤᱡᱽ ᱚᱵᱚᱛᱟᱨ ᱵᱟᱪᱷᱟᱣ',
  youWillHearTheTranslationText:
      'ᱟᱢᱮᱢ ᱵᱟᱪᱷᱟᱣ ᱟᱠᱟᱫᱮ ᱚᱵᱚᱛᱟᱨᱟᱜ ᱟᱲᱟᱝᱛᱮ ᱛᱚᱨᱡᱚᱢᱟᱢ ᱟᱸᱡᱚᱢᱟ ᱾ ᱟᱢ ᱱᱚᱶᱟ ᱥᱟᱨᱟ ᱵᱮᱲᱟᱜᱮ ᱥᱮᱴᱤᱝ ᱠᱷᱚᱱᱮᱢ ᱵᱚᱫᱚᱞ  ᱫᱟᱲᱮᱭᱟᱜᱼᱟ',
  male: 'ᱠᱚᱲᱟ',
  female: 'ᱛᱤᱨᱞᱟᱹ',
  letsTranslate: 'ᱛᱚᱨᱡᱚᱢᱟ ᱞᱮᱜᱮᱵᱚᱱ',
  appTheme: 'ᱮᱯ ᱛᱷᱤᱢ',
  appInterfaceWillChange: 'ᱵᱟᱪᱷᱟᱣᱟᱠᱟᱱ ᱢᱳᱰ ᱞᱮᱠᱟᱜᱮ ᱮᱯ ᱤᱱᱴᱟᱨᱯᱷᱮᱥ ᱵᱚᱫᱚᱞᱚᱜᱼᱟ',
  light: 'ᱢᱟᱨᱥᱟᱞ',
  dark: 'ᱧᱩᱛᱟᱹᱫ',
  systemDefault: 'ᱥᱤᱥᱴᱟᱢ ᱰᱤᱯᱷᱚᱞᱴ',
  appLanguage: 'ᱮᱯ ᱯᱟᱹᱨᱥᱤ',
  appInterfaceWillChangeInSelected:
      'ᱵᱟᱪᱷᱟᱣᱟᱠᱟᱱ ᱮᱯ ᱯᱟᱹᱨᱥᱤᱨᱮ ᱮᱯ ᱤᱱᱴᱟᱨᱯᱷᱮᱥ ᱫᱚ ᱵᱚᱫᱚᱞᱚᱜᱼᱟ',
  voiceAssistant: 'ᱟᱲᱟᱝ ᱥᱚᱦᱚᱫᱤᱡᱽ',
  transLiteration: 'ᱟᱠᱷᱚᱨ ᱛᱚᱨᱡᱚᱢᱟᱭ',
  transLiterationWillInitiateWord:
      'ᱟᱢ ᱴᱟᱭᱤᱯ ᱚᱠᱛᱮ ᱟᱠᱷᱚᱨᱼᱛᱚᱨᱡᱚᱢᱟᱭ ᱫᱚ ᱟᱹᱲᱟᱹ ᱥᱟᱞᱦᱟᱭᱮ ᱮᱛᱚᱦᱚᱵᱟ',
  advanceSettings: 'ᱢᱟᱲᱟᱝ ᱥᱮᱴᱤᱝ',
  kTranslation: 'ᱛᱚᱨᱡᱚᱢᱟ',
  kChat: 'ᱪᱮᱴ',
  kSettings: 'ᱥᱮᱴᱤᱝ',
  kHomeLoadingAnimationText: 'ᱥᱟᱵ ᱦᱟᱛᱟᱲ, ᱟᱞᱮ ᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱡᱤᱱᱤᱥᱞᱮ ᱥᱮᱴᱤᱝ ᱮᱫᱟ',
  kTranslateSourceTitle: 'ᱠᱷᱚᱱ ᱛᱚᱨᱡᱚᱢᱟ',
  kTranslateTargetTitle: 'ᱨᱮ ᱛᱚᱨᱡᱚᱢᱟ',
  kTranslationHintText: 'ᱴᱟᱭᱤᱯᱤᱝ ᱮᱛᱚᱦᱚᱵ ᱥᱮ ᱮᱛᱚᱦᱚᱵ ᱞᱟᱹᱜᱤᱫ ᱢᱟᱹᱭᱤᱠ ᱚᱛᱟ',
  kListeningHintText: 'ᱟᱸᱡᱚᱢᱤᱫᱟᱹᱧ, ᱱᱤᱛᱚᱜ ᱨᱚᱲ ᱢᱮ',
  kPaste: 'ᱛᱷᱚᱯᱨᱟᱢ',
  kTranslate: 'ᱛᱚᱨᱡᱚᱢᱟ',
  kReset: 'ᱫᱚᱲᱦᱟ ᱵᱟᱹᱭᱥᱟᱹᱣ',
  kErrorNoSourceText: 'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱞᱟᱦᱟ ᱴᱮᱠᱥᱴ ᱟᱫᱮᱨ ᱢᱮ',
  kErrorSelectSourceAndTargetScreen:
      'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱞᱟᱦᱟ ᱯᱷᱮᱰᱟᱛ ᱟᱨ ᱴᱷᱤᱠᱟᱹᱵᱩᱴᱟᱹ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
  errorMicPermission: 'ᱟᱲᱟᱝ ᱨᱮᱠᱚᱰᱤᱝ ᱞᱟᱹᱜᱤᱫ ᱢᱟᱹᱭᱤᱠ ᱨᱮᱭᱟᱜ ᱪᱷᱟᱹᱲ ᱞᱟᱹᱠᱛᱤᱭᱟ',
  errorInRecording: 'ᱦᱤᱲᱤᱡ ᱟᱲᱟᱝ ᱨᱮᱠᱚᱰᱤᱝ',
  noVoiceAssistantAvailable: 'ᱱᱮ ᱜᱷᱟᱹᱲᱤᱡ ᱟᱲᱟᱝ ᱥᱚᱦᱚᱫ ᱵᱟᱝ ᱧᱟᱢᱚᱜ ᱠᱟᱱᱟ',
  kTranslationLoadingAnimationText: 'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱛᱟᱹᱜᱤᱭᱢᱮ ᱛᱚᱨᱡᱚᱢᱟᱜ ᱠᱟᱱᱟ',
  errorPleaseSelectLanguage: 'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣᱢᱮ',
  featureAvailableSoonInfo: 'ᱱᱤᱭᱟᱹ ᱜᱚᱲᱦᱚᱱ ᱞᱚᱜᱚᱱ ᱧᱟᱢᱚᱜᱼᱟ',
  errorSelectVoiceAssistant: 'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱟᱲᱟᱝ ᱥᱚᱦᱚᱫ ᱚᱵᱚᱛᱟᱨ ᱵᱟᱪᱷᱟᱣ ᱮᱢ',
  noTextForShare: 'ᱥᱮᱭᱟᱨ ᱞᱟᱹᱜᱤᱫ ᱴᱮᱠᱥᱴ ᱵᱟᱝ ᱧᱟᱢᱚᱜ ᱠᱟᱱᱟ',
  noTextForCopy: 'ᱠᱚᱯᱤ ᱞᱟᱹᱜᱤᱫ ᱴᱮᱠᱥᱴ ᱵᱟᱝ ᱧᱟᱢᱚᱜ ᱠᱟᱱᱟ',
  textCopiedToClipboard: 'ᱠᱞᱤᱯᱵᱳᱰ ᱨᱮ ᱴᱮᱠᱥᱴ ᱱᱚᱠᱚᱞᱮᱱᱟ',
  femaleVoiceAssistantNotAvailable:
      'ᱛᱤᱨᱞᱟᱹ ᱟᱲᱟᱝ ᱥᱚᱦᱮᱫᱤᱭᱟᱹ ᱫᱚ ᱵᱟᱹᱱᱩᱜᱼᱟ, ᱠᱚᱲᱟ ᱟᱲᱟᱝ ᱥᱚᱦᱚᱫ ᱛᱮ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ',
  maleVoiceAssistantNotAvailable:
      'ᱠᱚᱲᱟ ᱟᱲᱟᱝ ᱥᱚᱦᱮᱫ ᱫᱚ ᱵᱟᱹᱱᱩᱜᱼᱟ,ᱛᱤᱨᱞᱟᱹ ᱟᱲᱟᱝ ᱥᱚᱦᱚᱫ ᱛᱮ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ',
  errorNoTextInClipboard: 'ᱠᱞᱤᱯᱵᱳᱰ ᱨᱮ ᱴᱮᱠᱥᱴ ᱵᱟᱝ ᱧᱟᱢᱚᱜᱼᱟ',
  s2sStreaming: 'ᱮᱥ ᱴᱩ ᱮᱥ ᱥᱴᱨᱤᱢᱤᱝ',
  connecting: 'ᱡᱚᱯᱚᱲᱟᱜ ᱠᱟᱱᱟᱹᱹᱹ',
  somethingWentWrong: 'ᱠᱤᱪᱷᱩ ᱜᱟᱹᱞᱛᱤ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ ',
  tapAndHoldForRecording: 'ᱫᱟᱭᱟᱠᱟᱛᱮ ᱨᱮᱠᱚᱰᱤᱝ ᱞᱟᱹᱜᱤᱫ ᱢᱟᱭᱤᱠ ᱥᱟᱵᱽ ᱟᱨ  ᱴᱮᱯᱢᱮ ',
  cannotPlayAudioAtTheMoment: 'ᱱᱤᱭᱟᱹ ᱚᱠᱛᱚ ᱳᱰᱤᱭᱳ ᱪᱟᱞᱟᱣ ᱵᱟᱝ ᱜᱟᱱᱚᱜ ᱠᱟᱱᱟ ',
  responseNotReceived: 'ᱦᱤᱲᱤᱡᱺ ᱛᱮᱞᱟ ᱵᱟᱝ ᱧᱟᱢᱟᱠᱟᱱᱟ',
  translationNotPossible: 'ᱱᱤᱭᱟᱹ ᱚᱠᱛᱚ ᱛᱚᱨᱡᱚᱢᱟᱭ ᱵᱟᱝ ᱜᱟᱱᱚᱜ ᱠᱟᱱᱟ ',
  bhashiniTitle: 'ᱵᱷᱟᱥᱤᱱᱤ ',
};
