import 'localization_keys.dart';

final Map<String, String> sd = {
  appName: 'भाषावर्स',
  selectAppLanguage: 'ऐप जी ॿोली चूंडियो',
  youCanAlwaysChange: 'तव्हां सेटिंग मां इन्हे खे कॾहिं बि मटे सघो था',
  searchLanguage: 'ॿोली ॻोल्हियो',
  continueText: 'जारी रहो',
  next: 'अॻियां',
  skip: 'स्किप कयो',
  getStarted: 'शुरू कयो',
  speechRecognition: 'वाणी सुञाणप',
  automaticallyRecognizeAndConvert:
      'पंहिंजी आवाज़ खे पाणमुरादो सुञाणो ऐं टेक्स्ट में तब्दीलु कयो',
  speechToSpeechTranslation: 'ज़ुबानी सां ज़ुबानी तर्जुमो',
  translateYourVoiceInOneIndianLanguage:
      'पंहिंजी आवाज़ खे हिक भारतीअ ॿोलीअ मां ॿिए भारतीअ ॿोलीअ में तर्जुमो कयो',
  languageTranslation: 'ॿोलीअ जो तर्जुमो',
  translateSentencesFromOneIndianLanguageToAnother:
      'सिटुनि खे हिक भारतीअ ॿोलीअ खां ॿिए भारतीअ ॿोलीअ में तर्जुमो कयो ',
  bhashaverseChatBot: 'भाषावर्स चैट बॉट',
  selectVoiceAssistant: 'आवाज़ी सहाइकु अवतार चूंडियो',
  youWillHearTheTranslationText:
      'तव्हां जे चूंडियल अवतार जी आवाज़ में तव्हां तर्जुमो ॿुधंदा। तव्हां सेटिंग मां कॾहिं बि अवतार मटे सघो था',
  male: 'मर्दु',
  female: 'औरत',
  letsTranslate: 'तर्जुमो कयूं',
  appTheme: 'ऐप थीम',
  appInterfaceWillChange: 'ऐप इंटरफ़ेस चूंडियल मोड मूजिब तब्दील थी वेंदो',
  light: 'सोझिरो',
  dark: 'ऊंदहि',
  systemDefault: 'सिस्टम डिफ़ॉल्ट',
  appLanguage: 'ऐप ॿोली',
  appInterfaceWillChangeInSelected:
      'ऐप इंटरफ़ेस चूंडियल ॿोलीअ में तब्दील थी वेंदो',
  voiceAssistant: 'आवाज़ी सहाइकु',
  transLiteration: 'लिप्यंतरण',
  transLiterationWillInitiateWord:
      'लिप्यंतरण तव्हां जे टाइप करण वक़्ति शब्द सलाह शुरू कंदो',
  advanceSettings: 'एडवांस सेटिंग',
  kTranslation: 'तर्जु्मो',
  kChat: 'ॻाल्हि करणु',
  kSettings: 'सेटिंग्स',
  kHomeLoadingAnimationText: 'तरिसो, असीं तव्हां लाइ शयूं सेट करे रहिया आहियूं',
  kTranslateSourceTitle: 'खां तर्जुमो कयो',
  kTranslateTargetTitle: 'में तर्जुमो कयो',
  kTranslationHintText: 'टाइप करणु शुरू कयो या शुरू करण लाइ माइक खे दॿायो',
  kListeningHintText: 'ॿुधूं पिया, हाण ॻाल्हायो',
  kPaste: 'पेस्ट',
  kTranslate: 'तर्जुमो',
  kReset: 'रीसेट',
  kErrorNoSourceText: 'मेहरबानी करे पहिरीं टेक्स्ट दर्ज कयो',
  kErrorSelectSourceAndTargetScreen:
      'मेहरबानी करे पहिरीं मूल ऐं तय-कयलु ॿोली चूंडियो',
  errorMicPermission: 'आवाज़ रिकॉर्ड करण लाइ माइक जी इजाज़त खपे',
  errorInRecording: 'आवाज़ रिकॉर्ड में चुक',
  noVoiceAssistantAvailable: 'हिन वक़्ति को बि आवाज़ी सहाइकु मौजूद नाहे',
  kTranslationLoadingAnimationText:
      'तर्जुमो थी रहियो आहे, मेहरबानी करे इंतज़ार कयो',
  errorPleaseSelectLanguage: 'मेहरबानी करे ॿोली चूंडियो',
  featureAvailableSoonInfo: 'इहा सहूलियत जल्दी मुयस्सरु थींदी',
  errorSelectVoiceAssistant: 'मेहरबानी करे आवाज़ी सहाइक अवतार चूंडियो',
  noTextForShare: 'शेयर करण लाइ टेक्स्ट न मिलियो',
  noTextForCopy: 'कॉपी करण लाइ टेक्स्ट न मिलियो',
  textCopiedToClipboard: 'क्लिपबोर्ड ते टेक्स्ट कॉपी कयो वियो',
  femaleVoiceAssistantNotAvailable:
      'ज़नानो आवाज़ी सहाइकु मौजूद नाहे, मर्दानो आवाज़ी सहाइकु सां हली रहियो आहे',
  maleVoiceAssistantNotAvailable:
      'मर्दानो आवाज़ी सहाइकु मौजूद नाहे, ज़नानो आवाज़ी सहाइकु सां हली रहियो आहे',
  errorNoTextInClipboard: 'क्लिपबोर्ड में टेक्स्ट मौजूद नाहे ',
  s2sStreaming: 'एस2एस स्ट्रीमिंग थी रही आहे',
  connecting: 'कनेक्ट थी रहियो आहे...',
  somethingWentWrong: 'कुझु ग़लतु थियो',
  tapAndHoldForRecording: 'रिकार्डींग लाइ महरबानी करे माइक खे टैप करे झले रखो ',
  cannotPlayAudioAtTheMoment: 'हिन वक़्ति आवाज़ न हली सघंदो',
  responseNotReceived: 'चूकः वरंदी हासिलु न थी',
  translationNotPossible: 'तर्जुमो हिन वक़्त मुम्किन नाहे',
  bhashiniTitle: 'भाशिणी',
  bhashiniChatBot: 'भाशिणी चैट बोट',
};
