import 'localization_keys.dart';

final Map<String, String> te = {
  appName: 'భాషావెర్స్',
  selectAppLanguage: 'ఆప్ యొక్క భాషను ఎంచుకోండి',
  youCanAlwaysChange: 'దీనిని సెటింగ్స్ నుండి ఎల్లప్పుడూ మార్చుకోవచ్చు',
  searchLanguage: 'భాషను వెతకండి',
  continueText: 'కొనసాగండి',
  next: 'తరువాత',
  skip: 'స్కిప్ చేయండి',
  getStarted: 'ఆరంభించండి',
  speechRecognition: 'మాటలను గుర్తించు',
  automaticallyRecognizeAndConvert:
      'స్వయంచాలకంగా మీ మాటలను గుర్తించి, టెక్స్ట్ రూపంలోకి మార్చు',
  speechToSpeechTranslation: 'మాటల నుండి మాటలకు అనువదించు',
  translateYourVoiceInOneIndianLanguage:
      'మీ మాటలను ఒక భారతీయ భాష నుండి మరొక దానికి అనువదించండి',
  languageTranslation: 'భాష అనువాదం',
  translateSentencesFromOneIndianLanguageToAnother:
      'వాక్యాలను ఒక భారతీయ భాష నుండి మరొక దానికి అనువదించు',
  bhashaverseChatBot: 'భాషావెర్స్ చాట్ బాట్',
  selectVoiceAssistant: 'వాయిస్ అసిస్టెంట్ అవతార్ ని ఎంచుకోండి',
  youWillHearTheTranslationText:
      'మీరు ఎంచుకున్న అవతార్ యొక్క స్వరంలో అనువాదాన్ని వింటారు. మీరు అవతార్ ని సెటింగ్స్ నుండి ఎల్లప్పుడూ మార్చుకోవచ్చు',
  male: 'మగ',
  female: 'ఆడ',
  letsTranslate: 'అనువదించుదాం',
  appTheme: 'ఆప్ యొక్క థీం',
  appInterfaceWillChange: 'మీరు ఎంచుకున్న పద్ధతిలోకి ఆప్ ఇంటర్ఫేస్ మారుతుంది',
  light: 'లేత రంగు',
  dark: 'ముదురు రంగు',
  systemDefault: 'సిస్టం అప్రమేయం',
  appLanguage: 'ఆప్ యొక్క భాష ',
  appInterfaceWillChangeInSelected: 'ఆప్ యొక్క భాషలోకి ఇంటర్ఫేస్ మారుతుంది',
  voiceAssistant: 'వాయిస్ అసిస్టెంట్',
  transLiteration: 'లిప్యంతరీకరణ',
  transLiterationWillInitiateWord:
      'మీరు టైపు చేస్తున్నప్పుడు లిప్యంతరీకరణ మాటలను సూచించటం ఆరంభిస్తుంది',
  advanceSettings: 'ఉన్నత సెట్టింగులు',
  kTranslation: 'అనువాదం',
  kChat: 'చాట్',
  kSettings: 'సెట్టింగులు',
  kHomeLoadingAnimationText: 'ఆగండి, మీకు విషయాలను సిద్ధం చేస్తున్నాము',
  kTranslateSourceTitle: 'నుండి అనువదించు',
  kTranslateTargetTitle: 'కి అనువదించు',
  kTranslationHintText:
      'ప్రారంభించటానికి టైపు చేయటం ఆరంభించండి లేక మైక్ పై నొక్కండి',
  kListeningHintText: 'వింటున్నాము, ఇప్పుడు మాట్లాడండి',
  kPaste: 'అతికించండి',
  kTranslate: 'అనువదించు',
  kReset: 'రీసెట్ చేయి',
  kErrorNoSourceText: 'దయచేసి ముందుగా టెక్స్ట్ ను ఎంటర్ చేయండి ',
  kErrorSelectSourceAndTargetScreen:
      'దయచేసి ముందుగా మూలాన్ని మరియు మీకు కావలసిన భాషను ఎంచుకోండి ',
  errorMicPermission: 'ధ్వని రికార్డు చేయటానికి మైక్ కి అనుమతి ఇవ్వండి',
  errorInRecording: 'ధ్వని రికార్డు అవడంలో పొరపాటు',
  noVoiceAssistantAvailable: 'ఈ సమయంలో వాయిస్ అసిస్టెంట్ లభ్యముగా లేదు',
  kTranslationLoadingAnimationText: 'అనువదించబడుతోంది, దయచేసి వేచి ఉండండి ',
  errorPleaseSelectLanguage: 'దయచేసి భాషను ఎంచుకోండి',
  featureAvailableSoonInfo: 'ఈ ఫీచర్ త్వరలో లభ్యమౌతుంది',
  errorSelectVoiceAssistant: 'దయచేసి వాయిస్ అసిస్టెంట్ అవతార్ ని ఎంచుకోండి',
  noTextForShare: 'షేర్ చేయటానికి టెక్స్ట్ కనబడలేదు',
  noTextForCopy: 'కాపీ చేయటానికి టెక్స్ట్ కనబడలేదు',
  textCopiedToClipboard: 'టెక్స్ట్ క్లిప్ బోర్డ్ కి కాపీ చేయబడింది',
  femaleVoiceAssistantNotAvailable:
      'ఆడ వాయిస్ అసిస్టెంట్ లభ్యముగా లేదు, మగ వాయిస్ అసిస్టెంట్ తో వినిపించబడుతోంది',
  maleVoiceAssistantNotAvailable:
      'మగ వాయిస్ అసిస్టెంట్ లభ్యముగా లేదు, ఆడ వాయిస్ అసిస్టెంట్ తో వినిపించబడుతోంది',
  errorNoTextInClipboard: 'క్లిప్ బోర్డ్ లో టెక్స్ట్ లభ్యముగా లేదు',
  s2sStreaming: 'S2S స్ట్రీమింగ్',
  connecting: 'అనుసంధానిస్తోంది...',
  somethingWentWrong: 'ఎదో పొరపాటు జరిగింది',
  tapAndHoldForRecording: 'రికార్డు చేయటానికి దయచేసి మైక్‌ను నొక్కి పట్టుకోండి',
  cannotPlayAudioAtTheMoment: 'ప్రస్తుత సమయంలో ధ్వని వినిపించటం వీలుపడదు',
  responseNotReceived: 'పొరపాటు: ప్రతిస్పందన లభించలేదు',
  translationNotPossible: 'ప్రస్తుత సమయంలో  అనువాదం వీలు పడదు ',
  bhashiniTitle: 'భాషిణి',
};
