import 'localization_keys.dart';

final Map<String, String> ur = {
  appName: 'بھاشاورس',
  selectAppLanguage: 'ایپ کی زبان منتخب کریں',
  youCanAlwaysChange: 'اسے آپ کبھی بھی ترتیبات سے تبدیل کر سکتے ہیں',
  searchLanguage: 'زبان تلاش کریں',
  continueText: 'جاری رکھیں',
  next: 'اگلا',
  skip: 'اسکپ کریں',
  getStarted: 'شروع کریں',
  speechRecognition: 'اسپیچ ریکگنیشن',
  automaticallyRecognizeAndConvert:
      'پنی آواز کو خودکار طور پر  پہچان کر متن میں تبدیل کریں',
  speechToSpeechTranslation: 'اسپیچ ٹو اسپیچ ترجمہ',
  translateYourVoiceInOneIndianLanguage:
      'اپنی آواز کا ایک ہندوستانی زبان سے دوسری میں ترجمہ کریں ',
  languageTranslation: 'ترجمۂ زبان',
  translateSentencesFromOneIndianLanguageToAnother:
      'جملوں کا ایک ہندوستانی زبان سے دوسری میں ترجمہ کریں',
  bhashaverseChatBot: 'بھاشاورس چیٹ بوٹ',
  selectVoiceAssistant: 'صوتی معاون اوتار منتخب کریں',
  youWillHearTheTranslationText:
      'آپ اپنے منتخب کردہ اوتار کی آواز میں ترجمہ سنیں گے۔ آپ ترتیبات سے کبھی بھی اوتار بدل سکتے ہیں۔',
  male: 'مرد',
  female: 'عورت ',
  letsTranslate: 'آئیے ترجمہ کریں',
  appTheme: 'ایپ کی تھیم',
  appInterfaceWillChange:
      'ایپ انٹرفیس منتخبہ موڈ میں اس کے مطابق تبدیل ہو جائے گا',
  light: 'ہلکا',
  dark: 'گہرا',
  systemDefault: 'سسٹم ڈیفالٹ',
  appLanguage: 'ایپ کی زبان',
  appInterfaceWillChangeInSelected:
      'ایپ انٹرفیس منتخبہ ایپ کی زبان میں تبدیل ہو جائے گا',
  voiceAssistant: 'صوتی معاون',
  transLiteration: 'نقل حرفی',
  transLiterationWillInitiateWord:
      'نقل حرفی آپ کے ٹائپ کرتے وقت لفظ کی تجاویز دینا شروع کرے گا',
  advanceSettings: ' اضافی ترتیبات',
  kTranslation: 'ترجمہ',
  kChat: 'چیٹ',
  kSettings: 'ترتیبات',
  kHomeLoadingAnimationText: 'ٹھہریں، ہم آپ کے لیے چیزیں ترتیب دے رہے ہیں',
  kTranslateSourceTitle: 'سے ترجمہ کریں',
  kTranslateTargetTitle: 'میں ترجمہ کریں',
  kTranslationHintText: 'ٹائپ کرنا شروع کریں یا مائک دبا کر آغاز کریں',
  kListeningHintText: 'سنا جا رہا ہے، اب آپ بولیں',
  kPaste: 'پیسٹ کریں',
  kTranslate: 'ترجمہ کریں',
  kReset: 'ری سیٹ کریں',
  kErrorNoSourceText: 'براہ کرم پہلے متن درج کریں',
  kErrorSelectSourceAndTargetScreen:
      'براہ کرم پہلے ماخذ اور ہدف زبان منتخب کریں',
  errorMicPermission: 'آواز ریکارڈ کرنے کے لیے مائک کی اجازت درکار ہے',
  errorInRecording: 'صوتی ریکارڈنگ میں خرابی',
  noVoiceAssistantAvailable: 'اس وقت کوئی صوتی معاون دستیاب نہیں ہے',
  kTranslationLoadingAnimationText: 'ترجمہ ہو رہا ہے، براہ کرم انتظار کریں',
  errorPleaseSelectLanguage: 'براہ کرم زبان منتخب کریں',
  featureAvailableSoonInfo: 'یہ فیچر جلد ہی دستیاب ہوگا',
  errorSelectVoiceAssistant: 'براہ کرم صوتی معاون اوتار منتخب کریں',
  noTextForShare: 'شیئر کرنے کے لیے کوئی متن نہیں ملا',
  noTextForCopy: 'کاپی کرنے کے لیے کوئی متن نہیں ملا',
  textCopiedToClipboard: 'متن کلپ بورڈ پر کاپی ہو گیا',
  femaleVoiceAssistantNotAvailable:
      'زنانہ صوتی معاون دستیاب نہیں ہے، مردانہ صوتی معاون سے چلایا جا رہا ہے',
  maleVoiceAssistantNotAvailable:
      'مردانہ صوتی معاون دستیاب نہیں ہے، زنانہ صوتی معاون سے چلایا جا رہا ہے',
  errorNoTextInClipboard: 'کلپ بورڈ میں کوئی متن دستیاب نہیں ہے',
  s2sStreaming: 'ایس ٹو ایس اسٹریمنگ ہو رہی ہے',
  connecting: 'کنیکٹ کیا جا رہا ہے',
  somethingWentWrong: 'کچھ غلط ہو گیا',
  tapAndHoldForRecording: 'ریکارڈ کرنے کے لیے مائک کو ٹیپ کریں اور ہولڈ کریں',
  cannotPlayAudioAtTheMoment: 'اس وقت آڈیو نہیں چل سکتا',
  responseNotReceived: 'خرابی: جواب موصول نہیں ہوا',
  translationNotPossible: 'اس وقت ترجمہ ممکن نہیں',
  bhashiniTitle: 'بھاشنی',
};
