List<String> languagesCodeList = [
  'en',
  'hi',
  'mr',
  'bn',
  'pa',
  'gu',
  'or',
  'ta',
  'te',
  'kn',
  'ur',
  'doi',
  'ne',
  'si',
  'sa',
  'as',
  'mai',
  'bho',
  'ml',
  'raj',
  'brx',
  'mni',
  'ks',
  'gom',
  'sd',
  'sat',
];

//Voice Screen

Set<String> voiceBetaSourceLang = {
  languagesCodeList[10],
  languagesCodeList[11],
  languagesCodeList[12],
  languagesCodeList[13],
  languagesCodeList[14],
  languagesCodeList[16],
  languagesCodeList[17],
  languagesCodeList[19],
  languagesCodeList[20],
  languagesCodeList[21],
  languagesCodeList[22],
  languagesCodeList[23],
  languagesCodeList[24],
  languagesCodeList[25],
};
Set<String> voiceBetaTargetLang = {
  languagesCodeList[10],
  languagesCodeList[11],
  languagesCodeList[12],
  languagesCodeList[13],
  languagesCodeList[14],
  languagesCodeList[16],
  languagesCodeList[17],
  languagesCodeList[19],
  languagesCodeList[20],
  languagesCodeList[21],
  languagesCodeList[22],
  languagesCodeList[23],
  languagesCodeList[24],
  languagesCodeList[25],
};

Set<String> voiceSkipSourceLang = {
  // languagesCodeList[10],
};
Set<String> voiceSkipTargetLang = {
  // languagesCodeList[20],
};

//Converse Screen

Set<String> converseBetaSourceLang = {
  languagesCodeList[10],
  languagesCodeList[11],
  languagesCodeList[12],
  languagesCodeList[13],
  languagesCodeList[14],
  languagesCodeList[16],
  languagesCodeList[17],
  languagesCodeList[19],
  languagesCodeList[20],
  languagesCodeList[21],
  languagesCodeList[22],
  languagesCodeList[23],
  languagesCodeList[24],
  languagesCodeList[25],
};
Set<String> converseBetaTargetLang = {
  languagesCodeList[10],
  languagesCodeList[11],
  languagesCodeList[12],
  languagesCodeList[13],
  languagesCodeList[14],
  languagesCodeList[16],
  languagesCodeList[17],
  languagesCodeList[19],
  languagesCodeList[20],
  languagesCodeList[21],
  languagesCodeList[22],
  languagesCodeList[23],
  languagesCodeList[24],
  languagesCodeList[25],
};

Set<String> converseSkipSourceLang = {
  // languagesCodeList[10],
};
Set<String> converseSkipTargetLang = {
  // languagesCodeList[20],
};

//Text Screen

Set<String> textBetaSourceLang = {
  languagesCodeList[10],
  languagesCodeList[11],
  languagesCodeList[12],
  languagesCodeList[13],
  languagesCodeList[14],
  languagesCodeList[16],
  languagesCodeList[17],
  languagesCodeList[19],
  languagesCodeList[20],
  languagesCodeList[21],
  languagesCodeList[22],
  languagesCodeList[23],
  languagesCodeList[24],
  languagesCodeList[25],
};

Set<String> textBetaTargetLang = {
  languagesCodeList[10],
  languagesCodeList[11],
  languagesCodeList[12],
  languagesCodeList[13],
  languagesCodeList[14],
  languagesCodeList[16],
  languagesCodeList[17],
  languagesCodeList[19],
  languagesCodeList[20],
  languagesCodeList[21],
  languagesCodeList[22],
  languagesCodeList[23],
  languagesCodeList[24],
  languagesCodeList[25],
};

Set<String> textSkipSourceLang = <String>{};
Set<String> textSkipTargetLang = <String>{};

class TranslatedLanguagesMap {
  static Map<String, Map<String, String>> language = {
    // English
    languagesCodeList[0]: {
      languagesCodeList[0]: 'English',
      languagesCodeList[1]: 'Hindi',
      languagesCodeList[2]: 'Marathi',
      languagesCodeList[3]: 'Bangla',
      languagesCodeList[4]: 'Punjabi',
      languagesCodeList[5]: 'Gujarati',
      languagesCodeList[6]: 'Odia',
      languagesCodeList[7]: 'Tamil',
      languagesCodeList[8]: 'Telugu',
      languagesCodeList[9]: 'Kannada',
      languagesCodeList[10]: 'Urdu',
      languagesCodeList[11]: 'Dogri',
      languagesCodeList[12]: 'Nepali',
      languagesCodeList[13]: 'Sinhala',
      languagesCodeList[14]: 'Sanskrit',
      languagesCodeList[15]: 'Assamese',
      languagesCodeList[16]: 'Maithili',
      languagesCodeList[17]: 'Bhojpuri',
      languagesCodeList[18]: 'Malayalam',
      languagesCodeList[19]: 'Rajasthani',
      languagesCodeList[20]: 'Bodo',
      languagesCodeList[21]: 'Manipuri',
      languagesCodeList[22]: 'Kashmiri',
      languagesCodeList[23]: 'Konkani',
      languagesCodeList[24]: 'Sindhi',
      languagesCodeList[25]: 'Santali',
    },
    // Hindi
    languagesCodeList[1]: {
      languagesCodeList[0]: 'अंग्रेजी',
      languagesCodeList[1]: 'हिंदी',
      languagesCodeList[2]: 'मराठी',
      languagesCodeList[3]: 'बांग्ला',
      languagesCodeList[4]: 'पंजाबी',
      languagesCodeList[5]: 'गुजराती',
      languagesCodeList[6]: 'ओड़िया',
      languagesCodeList[7]: 'तमिल',
      languagesCodeList[8]: 'तेलुगु',
      languagesCodeList[9]: 'कन्नड़',
      languagesCodeList[10]: 'उर्दू',
      languagesCodeList[11]: 'डोगरी',
      languagesCodeList[12]: 'नेपाली',
      languagesCodeList[13]: 'सिंहली',
      languagesCodeList[14]: 'संस्कृत',
      languagesCodeList[15]: 'असमिया',
      languagesCodeList[16]: 'मैथिली',
      languagesCodeList[17]: 'भोजपुरी',
      languagesCodeList[18]: 'मलयालम',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'मणिपुरी',
      languagesCodeList[22]: 'कश्मीरी',
      languagesCodeList[23]: 'कोंकणी',
      languagesCodeList[24]: 'सिंधी',
      languagesCodeList[25]: 'संथाली'
    },
    // Marathi
    languagesCodeList[2]: {
      languagesCodeList[0]: 'इंग्रजी ',
      languagesCodeList[1]: 'हिंदी ',
      languagesCodeList[2]: 'मराठी ',
      languagesCodeList[3]: 'बंगाली ',
      languagesCodeList[4]: 'पंजाबी ',
      languagesCodeList[5]: 'गुजराती ',
      languagesCodeList[6]: 'उडिया ',
      languagesCodeList[7]: 'तमिळ ',
      languagesCodeList[8]: 'तेलुगू ',
      languagesCodeList[9]: 'कानडी ',
      languagesCodeList[10]: 'उर्दू ',
      languagesCodeList[11]: 'डोगरी ',
      languagesCodeList[12]: 'नेपाळी ',
      languagesCodeList[13]: 'सिंहली ',
      languagesCodeList[14]: 'संस्कृत ',
      languagesCodeList[15]: 'आसामी ',
      languagesCodeList[16]: 'मैथिली ',
      languagesCodeList[17]: 'भोजपुरी ',
      languagesCodeList[18]: 'मल्याळम',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'मणिपुरी ',
      languagesCodeList[22]: 'काश्मिरी ',
      languagesCodeList[23]: 'कोंकणी ',
      languagesCodeList[24]: 'सिंधी ',
      languagesCodeList[25]: ''
    },
    // Bangla
    languagesCodeList[3]: {
      languagesCodeList[0]: 'ইংরেজি',
      languagesCodeList[1]: 'হিন্দি',
      languagesCodeList[2]: 'মারাঠি',
      languagesCodeList[3]: 'বাংলা',
      languagesCodeList[4]: 'পাঞ্জাবি',
      languagesCodeList[5]: 'গুজরাটি',
      languagesCodeList[6]: 'ওড়িয়া',
      languagesCodeList[7]: 'তামিল',
      languagesCodeList[8]: 'তেলুগু',
      languagesCodeList[9]: 'কন্নড়',
      languagesCodeList[10]: 'উর্দূ',
      languagesCodeList[11]: 'ডোগরি',
      languagesCodeList[12]: 'নেপালি',
      languagesCodeList[13]: 'সিংহলি',
      languagesCodeList[14]: 'সংস্কৃত',
      languagesCodeList[15]: 'অসমীয়া',
      languagesCodeList[16]: 'মৈথিলি',
      languagesCodeList[17]: 'ভোজপুরি',
      languagesCodeList[18]: 'মালয়ালম',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'মণিপুরি',
      languagesCodeList[22]: 'কাশ্মীরি',
      languagesCodeList[23]: 'কোঙ্কনি',
      languagesCodeList[24]: 'সিন্ধি',
      languagesCodeList[25]: 'সাঁওতালি'
    },
    //Punjabi
    languagesCodeList[4]: {
      languagesCodeList[0]: 'ਅੰਗਰੇਜ਼ੀ',
      languagesCodeList[1]: 'ਹਿੰਦੀ',
      languagesCodeList[2]: 'ਮਰਾਠੀ',
      languagesCodeList[3]: 'ਬੰਗਲਾ',
      languagesCodeList[4]: 'ਪੰਜਾਬੀ',
      languagesCodeList[5]: 'ਗੁਜਰਾਤੀ',
      languagesCodeList[6]: 'ਓਡੀਆ',
      languagesCodeList[7]: 'ਤਾਮਿਲ',
      languagesCodeList[8]: 'ਤੇਲਗੂ',
      languagesCodeList[9]: 'ਕੰਨੜ',
      languagesCodeList[10]: 'ਉਰਦੂ',
      languagesCodeList[11]: 'ਡੋਗਰੀ',
      languagesCodeList[12]: 'ਨੇਪਾਲੀ',
      languagesCodeList[13]: 'ਸਿੰਹਾਲਾ',
      languagesCodeList[14]: 'ਸੰਸਕ੍ਰਿਤ',
      languagesCodeList[15]: 'ਅਸਾਮੀ',
      languagesCodeList[16]: 'ਮੈਥਿਲੀ',
      languagesCodeList[17]: 'ਭੋਜਪੁਰੀ',
      languagesCodeList[18]: 'ਮਲਿਆਲਮ',
      languagesCodeList[19]: 'ਰਾਜਸਥਾਨੀ',
      languagesCodeList[20]: 'ਬੋਡੋ',
      languagesCodeList[21]: 'ਮਣੀਪੁਰੀ',
      languagesCodeList[22]: 'ਕਸ਼ਮੀਰੀ',
      languagesCodeList[23]: 'ਕੋਂਕਣੀ',
      languagesCodeList[24]: 'ਸਿੰਧੀ',
      languagesCodeList[25]: 'ਸੰਥਾਲੀ',
    },
    //Gujarati
    languagesCodeList[5]: {
      languagesCodeList[0]: 'અંગ્રેજી',
      languagesCodeList[1]: 'હિંદી',
      languagesCodeList[2]: 'મરાઠી',
      languagesCodeList[3]: 'બંગાળી',
      languagesCodeList[4]: 'પંજાબી',
      languagesCodeList[5]: 'ગુજરાતી ',
      languagesCodeList[6]: 'ઓડિયા',
      languagesCodeList[7]: 'તમિલ',
      languagesCodeList[8]: 'તેલુગુ',
      languagesCodeList[9]: 'કન્નડ ',
      languagesCodeList[10]: 'ઊર્દૂ ',
      languagesCodeList[11]: 'ડોગરી',
      languagesCodeList[12]: 'નેપાળી',
      languagesCodeList[13]: 'સિંહલી',
      languagesCodeList[14]: 'સંસ્કૃત',
      languagesCodeList[15]: 'અસમિયા',
      languagesCodeList[16]: 'મૈથિલી',
      languagesCodeList[17]: 'ભોજપુરી',
      languagesCodeList[18]: 'મલયાલમ',
      languagesCodeList[19]: 'રાજસ્થાની',
      languagesCodeList[20]: 'બોડો',
      languagesCodeList[21]: 'મણિપુરી',
      languagesCodeList[22]: 'કાશ્મીરી',
      languagesCodeList[23]: 'કોંકણી',
      languagesCodeList[24]: 'સિંધી',
      languagesCodeList[25]: 'સંતાલી',
    },
    // Odia
    languagesCodeList[6]: {
      languagesCodeList[0]: 'ଇଂରାଜୀ',
      languagesCodeList[1]: 'ହିନ୍ଦୀ',
      languagesCodeList[2]: 'ମରାଠୀ',
      languagesCodeList[3]: 'ବାଂଲା',
      languagesCodeList[4]: 'ପଞ୍ଜାବୀ',
      languagesCodeList[5]: 'ଗୁଜରାଟୀ',
      languagesCodeList[6]: 'ଓଡ଼ିଆ',
      languagesCodeList[7]: 'ତାମିଲ',
      languagesCodeList[8]: 'ତେଲୁଗୁ',
      languagesCodeList[9]: 'କନ୍ନଡ଼',
      languagesCodeList[10]: 'ଉର୍ଦ୍ଦୁ',
      languagesCodeList[11]: 'ଡୋଗରୀ',
      languagesCodeList[12]: 'ନେପାଳୀ',
      languagesCodeList[13]: 'ସିଂହଳୀ',
      languagesCodeList[14]: 'ସଂସ୍କୃତ',
      languagesCodeList[15]: 'ଅସମିୟା',
      languagesCodeList[16]: 'ମୈଥିଳି',
      languagesCodeList[17]: 'ଭୋଜପୁରୀ',
      languagesCodeList[18]: 'ମାଲୟାଲମ',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'ମଣିପୁରୀ',
      languagesCodeList[22]: 'କାଶ୍ମିରୀ',
      languagesCodeList[23]: 'କୋଙ୍କଣୀ',
      languagesCodeList[24]: 'ସିନ୍ଧି',
      languagesCodeList[25]: 'ସାନ୍ତାଳୀ'
    },
    // Tamil
    languagesCodeList[7]: {
      languagesCodeList[0]: 'ஆங்கிலம்',
      languagesCodeList[1]: 'ஹிந்தி',
      languagesCodeList[2]: 'மராத்தி',
      languagesCodeList[3]: 'பெங்காலி',
      languagesCodeList[4]: 'பஞ்சாபி',
      languagesCodeList[5]: 'குஜராத்தி',
      languagesCodeList[6]: 'ஒரியா',
      languagesCodeList[7]: 'தமிழ்',
      languagesCodeList[8]: 'தெலுங்கு',
      languagesCodeList[9]: 'கன்னடம்',
      languagesCodeList[10]: 'உருது',
      languagesCodeList[11]: 'டோக்ரி',
      languagesCodeList[12]: 'நேபாளி',
      languagesCodeList[13]: 'சிங்களம்',
      languagesCodeList[14]: 'சமஸ்கிருதம்',
      languagesCodeList[15]: 'அசாமி',
      languagesCodeList[16]: 'மைதிலி',
      languagesCodeList[17]: 'போஜ்புரி',
      languagesCodeList[18]: 'மலையாளம்',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'மணிப்பூரி',
      languagesCodeList[22]: 'காஷ்மீரி',
      languagesCodeList[23]: 'கொங்கனி',
      languagesCodeList[24]: 'சிந்தி',
      languagesCodeList[25]: 'சந்தாலி'
    },
    // Telugu
    languagesCodeList[8]: {
      languagesCodeList[0]: 'ఆంగ్లము',
      languagesCodeList[1]: 'హిందీ',
      languagesCodeList[2]: 'మరాఠి',
      languagesCodeList[3]: 'బంగ్లా',
      languagesCodeList[4]: 'పంజాబీ',
      languagesCodeList[5]: 'గుజరాతీ',
      languagesCodeList[6]: 'ఒడియా',
      languagesCodeList[7]: 'తమిళ్',
      languagesCodeList[8]: 'తెలుగు',
      languagesCodeList[9]: 'కన్నడ',
      languagesCodeList[10]: 'ఉర్దూ',
      languagesCodeList[11]: 'డోగ్రీ',
      languagesCodeList[12]: 'నేపాలీ',
      languagesCodeList[13]: 'సింహళ',
      languagesCodeList[14]: 'సంస్కృతం',
      languagesCodeList[15]: 'ఆసామీస్',
      languagesCodeList[16]: 'మైథిలి',
      languagesCodeList[17]: 'భోజ్‌పురీ',
      languagesCodeList[18]: 'మలయాళం',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'మణిపురీ',
      languagesCodeList[22]: 'కాశ్మీరీ',
      languagesCodeList[23]: 'కొంకణీ',
      languagesCodeList[24]: 'సింధీ',
      languagesCodeList[25]: 'సంతాలీ'
    },
    // Kannada
    languagesCodeList[9]: {
      languagesCodeList[0]: 'ಆಂಗ್ಲ',
      languagesCodeList[1]: 'ಹಿಂದಿ',
      languagesCodeList[2]: 'ಮರಾಠಿ',
      languagesCodeList[3]: 'ಬಾಂಗ್ಲಾ',
      languagesCodeList[4]: 'ಪಂಜಾಬಿ',
      languagesCodeList[5]: 'ಗುಜರಾತಿ',
      languagesCodeList[6]: 'ಒಡಿಯಾ',
      languagesCodeList[7]: 'ತಮಿಳು',
      languagesCodeList[8]: 'ತೆಲುಗು',
      languagesCodeList[9]: 'ಕನ್ನಡ',
      languagesCodeList[10]: 'ಉರ್ದು',
      languagesCodeList[11]: 'ಡೋಗ್ರಿ',
      languagesCodeList[12]: 'ನೇಪಾಳಿ',
      languagesCodeList[13]: 'ಸಿಂಹಳ',
      languagesCodeList[14]: 'ಸಂಸ್ಕೃತ',
      languagesCodeList[15]: 'ಅಸ್ಸಾಮಿ',
      languagesCodeList[16]: 'ಮೈಥಿಲಿ',
      languagesCodeList[17]: 'ಭೋಜಪುರಿ',
      languagesCodeList[18]: 'ಮಲಯಾಳಂ',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'ಮಣಿಪುರಿ',
      languagesCodeList[22]: 'ಕಾಶ್ಮೀರಿ',
      languagesCodeList[23]: 'ಕೊಂಕಣಿ',
      languagesCodeList[24]: 'ಸಿಂಧಿ',
      languagesCodeList[25]: 'ಸಂತಾಲಿ'
    },
    // Urdu
    languagesCodeList[10]: {
      languagesCodeList[0]: 'انگریزی',
      languagesCodeList[1]: 'ہندی',
      languagesCodeList[2]: 'مراٹھی',
      languagesCodeList[3]: 'بنگلہ',
      languagesCodeList[4]: 'پنجابی',
      languagesCodeList[5]: 'گجراتی',
      languagesCodeList[6]: 'اوڈیا',
      languagesCodeList[7]: 'تامل',
      languagesCodeList[8]: 'تیلگو',
      languagesCodeList[9]: 'کنڑ',
      languagesCodeList[10]: 'اردو',
      languagesCodeList[11]: 'ڈوگری',
      languagesCodeList[12]: 'نیپالی',
      languagesCodeList[13]: 'سنہالی',
      languagesCodeList[14]: 'سنسکرت',
      languagesCodeList[15]: 'آسامی',
      languagesCodeList[16]: 'میتھلی',
      languagesCodeList[17]: 'بھوجپوری',
      languagesCodeList[18]: 'ملیالم',
      languagesCodeList[19]: 'راجستھانی',
      languagesCodeList[20]: 'بوڈو',
      languagesCodeList[21]: 'منی پوری',
      languagesCodeList[22]: 'کشمیری',
      languagesCodeList[23]: 'کونکنی',
      languagesCodeList[24]: 'سندھی',
      languagesCodeList[25]: 'سنتالی',
    },
    // Dogri
    languagesCodeList[11]: {
      languagesCodeList[0]: 'अंग्रेज़ी',
      languagesCodeList[1]: 'हिंदी',
      languagesCodeList[2]: 'मराठी',
      languagesCodeList[3]: 'बंग्ला',
      languagesCodeList[4]: 'पंजाबी',
      languagesCodeList[5]: 'गुजराती',
      languagesCodeList[6]: 'उड़िया',
      languagesCodeList[7]: 'तमिल',
      languagesCodeList[8]: 'तेलुगु',
      languagesCodeList[9]: 'कन्नड़',
      languagesCodeList[10]: 'उर्दू',
      languagesCodeList[11]: 'डोगरी',
      languagesCodeList[12]: ' नेपाली',
      languagesCodeList[13]: 'सिंहली',
      languagesCodeList[14]: 'संस्कृत',
      languagesCodeList[15]: 'असमिया',
      languagesCodeList[16]: 'मैथली',
      languagesCodeList[17]: 'भोजपुरी',
      languagesCodeList[18]: 'मलयालम',
      languagesCodeList[19]: 'राजस्थानी',
      languagesCodeList[20]: 'बोडो',
      languagesCodeList[21]: 'मणिपुरी',
      languagesCodeList[22]: 'कश्मीरी',
      languagesCodeList[23]: 'कोंकणी',
      languagesCodeList[24]: ' सिंधी',
      languagesCodeList[25]: 'संथाली'
    },
    // Nepali
    languagesCodeList[12]: {
      languagesCodeList[0]: 'अङ्ग्रेजी',
      languagesCodeList[1]: 'हिन्दी',
      languagesCodeList[2]: 'मराठी',
      languagesCodeList[3]: 'बङ्गाली',
      languagesCodeList[4]: 'पन्जाबी',
      languagesCodeList[5]: 'गुजराती',
      languagesCodeList[6]: 'ओडिया',
      languagesCodeList[7]: 'तमिल',
      languagesCodeList[8]: 'तेलेगु',
      languagesCodeList[9]: 'कन्नडा',
      languagesCodeList[10]: 'उर्दू',
      languagesCodeList[11]: 'डोगरी',
      languagesCodeList[12]: 'नेपाली',
      languagesCodeList[13]: 'सिंहला',
      languagesCodeList[14]: 'संस्कृत',
      languagesCodeList[15]: 'असमिया',
      languagesCodeList[16]: 'मैथिली',
      languagesCodeList[17]: 'भोजपुरी',
      languagesCodeList[18]: 'मलायालम',
      languagesCodeList[19]: 'राजस्थानी',
      languagesCodeList[20]: 'बोडो',
      languagesCodeList[21]: 'मणिपुरी',
      languagesCodeList[22]: 'काश्मिरी',
      languagesCodeList[23]: 'कोङ्कणी',
      languagesCodeList[24]: 'सिन्धी',
      languagesCodeList[25]: 'सन्ताली',
    },
    // Sanskrit
    languagesCodeList[14]: {
      languagesCodeList[0]: 'आङ्ग्ला',
      languagesCodeList[1]: 'हिन्दी',
      languagesCodeList[2]: 'मराठी',
      languagesCodeList[3]: 'बाङ्ग्ला',
      languagesCodeList[4]: 'पञ्जाबी',
      languagesCodeList[5]: 'गुजराती',
      languagesCodeList[6]: 'ओडिया',
      languagesCodeList[7]: 'तमिळु',
      languagesCodeList[8]: 'तेलुगु',
      languagesCodeList[9]: 'कन्नडा',
      languagesCodeList[10]: 'उर्दू',
      languagesCodeList[11]: 'डोग्री',
      languagesCodeList[12]: 'नेपाली',
      languagesCodeList[13]: 'सिंहला',
      languagesCodeList[14]: 'संस्कृतम्',
      languagesCodeList[15]: 'अस्सामी',
      languagesCodeList[16]: 'मैथिली',
      languagesCodeList[17]: 'भोजपुरी',
      languagesCodeList[18]: 'मलयाळम्',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'मणिपुरी',
      languagesCodeList[22]: 'काश्मीरी',
      languagesCodeList[23]: 'कङ्कणी',
      languagesCodeList[24]: 'सिन्धी',
      languagesCodeList[25]: 'सन्तली'
    },
    // Assamese
    languagesCodeList[15]: {
      languagesCodeList[0]: 'ইংৰাজী',
      languagesCodeList[1]: 'হিন্দী',
      languagesCodeList[2]: 'মাৰাঠী',
      languagesCodeList[3]: 'বাংলা',
      languagesCodeList[4]: 'পাঞ্জাবী',
      languagesCodeList[5]: 'গুজৰাটী',
      languagesCodeList[6]: 'ওড়িয়া',
      languagesCodeList[7]: 'তামিল',
      languagesCodeList[8]: 'তেলেগু',
      languagesCodeList[9]: 'কন্নড়',
      languagesCodeList[10]: 'উৰ্দু',
      languagesCodeList[11]: 'ডোগ্ৰী',
      languagesCodeList[12]: 'নেপালী',
      languagesCodeList[13]: 'সিংহলি',
      languagesCodeList[14]: 'সংস্কৃত',
      languagesCodeList[15]: 'অসমীয়া',
      languagesCodeList[16]: 'মৈথিলী',
      languagesCodeList[17]: 'ভোজপুৰী',
      languagesCodeList[18]: 'মালয়ালম',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'মণিপুৰী',
      languagesCodeList[22]: 'কাশ্মিৰী',
      languagesCodeList[23]: 'কোংকণী',
      languagesCodeList[24]: 'সিন্ধী',
      languagesCodeList[25]: 'চাঁওতালি'
    },
    // Maithili
    languagesCodeList[16]: {
      languagesCodeList[0]: 'अङरेजी',
      languagesCodeList[1]: 'हिन्दी',
      languagesCodeList[2]: 'मराठी',
      languagesCodeList[3]: 'बाङ्गला',
      languagesCodeList[4]: 'पञ्जाबी',
      languagesCodeList[5]: 'गुजराती',
      languagesCodeList[6]: 'ओड़िया',
      languagesCodeList[7]: 'तमिल',
      languagesCodeList[8]: 'तेलुगु',
      languagesCodeList[9]: 'कन्नड़',
      languagesCodeList[10]: 'उर्दू',
      languagesCodeList[11]: 'डोगरी',
      languagesCodeList[12]: 'नेपाली',
      languagesCodeList[13]: 'सिंहली',
      languagesCodeList[14]: 'संस्कृत',
      languagesCodeList[15]: 'असमिया',
      languagesCodeList[16]: 'मैथिली',
      languagesCodeList[17]: 'भोजपुरी',
      languagesCodeList[18]: 'मलयालम',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'मणिपुरी',
      languagesCodeList[22]: 'कश्मीरी',
      languagesCodeList[23]: 'कोङ्कणी',
      languagesCodeList[24]: 'सिन्धी',
      languagesCodeList[25]: 'संथाली'
    },
    // Bhojpuri
    languagesCodeList[17]: {
      languagesCodeList[0]: 'अंग्रेजी',
      languagesCodeList[1]: 'हिंदी',
      languagesCodeList[2]: 'मराठी',
      languagesCodeList[3]: 'बांग्ला',
      languagesCodeList[4]: 'पंजाबी',
      languagesCodeList[5]: 'गुजराती',
      languagesCodeList[6]: 'ओड़िया',
      languagesCodeList[7]: 'तमिल',
      languagesCodeList[8]: 'तेलुगु',
      languagesCodeList[9]: 'कन्नड़',
      languagesCodeList[10]: 'उर्दू',
      languagesCodeList[11]: 'डोगरी',
      languagesCodeList[12]: 'नेपाली',
      languagesCodeList[13]: 'सिंहली',
      languagesCodeList[14]: 'संस्कृत',
      languagesCodeList[15]: 'असमिया',
      languagesCodeList[16]: 'मैथिली',
      languagesCodeList[17]: 'भोजपुरी',
      languagesCodeList[18]: 'मलयालम',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'मणिपुरी',
      languagesCodeList[22]: 'कश्मीरी',
      languagesCodeList[23]: 'कोंकणी',
      languagesCodeList[24]: 'सिंधी',
      languagesCodeList[25]: 'संथाली'
    },
    // Malayalam
    languagesCodeList[18]: {
      languagesCodeList[0]: 'ഇംഗ്ലീഷ്',
      languagesCodeList[1]: 'ഹിന്ദി',
      languagesCodeList[2]: 'മറാത്തി',
      languagesCodeList[3]: 'ബംഗ്ല',
      languagesCodeList[4]: 'പഞ്ചാബി',
      languagesCodeList[5]: 'ഗുജറാത്തി',
      languagesCodeList[6]: 'ഒറിയ',
      languagesCodeList[7]: 'തമിഴ്',
      languagesCodeList[8]: 'തെലുങ്ക്',
      languagesCodeList[9]: 'കന്നഡ',
      languagesCodeList[10]: 'ഉർദു',
      languagesCodeList[11]: 'ഡോഗ്‌രി',
      languagesCodeList[12]: 'നേപ്പാളി',
      languagesCodeList[13]: 'സിംഹള',
      languagesCodeList[14]: 'സംസ്കൃതം',
      languagesCodeList[15]: 'ആസാമീസ്',
      languagesCodeList[16]: 'മൈഥിലി',
      languagesCodeList[17]: 'ഭോജ്പൂരി',
      languagesCodeList[18]: 'മലയാളം',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'മണിപ്പൂരി',
      languagesCodeList[22]: 'കാഷ്മീരി',
      languagesCodeList[23]: 'കൊങ്കണി',
      languagesCodeList[24]: 'സിന്ധി',
      languagesCodeList[25]: 'സന്താളി'
    },
    // Manipuri
    languagesCodeList[21]: {
      languagesCodeList[0]: 'ꯏꯪꯒ꯭ꯔꯥꯖꯤ',
      languagesCodeList[1]: 'ꯍꯤꯟꯗꯤ',
      languagesCodeList[2]: 'ꯃꯔꯥꯊꯤ',
      languagesCodeList[3]: 'ꯕꯪꯒ꯭ꯂꯥ',
      languagesCodeList[4]: 'ꯄꯟꯖꯥꯕꯤ',
      languagesCodeList[5]: 'ꯒꯨꯖꯔꯥꯇꯤ',
      languagesCodeList[6]: 'ꯑꯣꯔꯤꯌꯥ',
      languagesCodeList[7]: 'ꯇꯃꯤꯜ',
      languagesCodeList[8]: 'ꯇꯦꯂꯨꯒꯨ',
      languagesCodeList[9]: 'ꯀꯟꯅꯥꯗꯥ',
      languagesCodeList[10]: 'ꯎꯔꯗꯨ',
      languagesCodeList[11]: 'ꯗꯣꯒ꯭ꯔꯤ',
      languagesCodeList[12]: 'ꯅꯦꯄꯥꯂꯤ',
      languagesCodeList[13]: 'ꯁꯤꯟꯍꯥꯂꯥ',
      languagesCodeList[14]: 'ꯁꯟꯁꯀ꯭ꯔꯤꯠ',
      languagesCodeList[15]: 'ꯑꯁꯥꯃꯤꯁ',
      languagesCodeList[16]: 'ꯃꯩꯊꯤꯂꯤ',
      languagesCodeList[17]: 'ꯚꯣꯖꯄꯨꯔꯤ',
      languagesCodeList[18]: 'ꯃꯂꯌꯥꯂꯝ',
      languagesCodeList[19]: '',
      languagesCodeList[20]: '',
      languagesCodeList[21]: 'ꯃꯅꯤꯄꯨꯔꯤ',
      languagesCodeList[22]: 'ꯀꯁꯃꯤꯔꯤ',
      languagesCodeList[23]: 'ꯀꯣꯟꯀꯅꯤ',
      languagesCodeList[24]: 'ꯁꯤꯟꯙꯤ',
      languagesCodeList[25]: 'ꯁꯟꯊꯥꯂꯤ'
    },
    // Kashmiri
    languagesCodeList[22]: {
      languagesCodeList[0]: 'انٛگلِش',
      languagesCodeList[1]: 'ہیٚندی',
      languagesCodeList[2]: 'مرٲٹھۍ',
      languagesCodeList[3]: 'بنگٲلۍ',
      languagesCodeList[4]: 'پنجٲبۍ',
      languagesCodeList[5]: 'گُجرٲتۍ',
      languagesCodeList[6]: 'اوڈیہ',
      languagesCodeList[7]: 'تٔمِل',
      languagesCodeList[8]: 'تیلگوٗ',
      languagesCodeList[9]: 'کَنَڈ',
      languagesCodeList[10]: 'اُردو',
      languagesCodeList[11]: 'ڈوٗگٕرۍ',
      languagesCodeList[12]: 'نیپٲلۍ',
      languagesCodeList[13]: 'سنہالا',
      languagesCodeList[14]: 'سنسکرٛت',
      languagesCodeList[15]: 'آسٲمۍ',
      languagesCodeList[16]: 'میتھلی',
      languagesCodeList[17]: 'بھوج پوٗری',
      languagesCodeList[18]: 'مٔلیٲلۍ',
      languagesCodeList[19]: 'راجستھٲنۍ',
      languagesCodeList[20]: 'بوڈو',
      languagesCodeList[21]: 'منیپوٗرۍ',
      languagesCodeList[22]: 'کٲشُتر',
      languagesCodeList[23]: 'کونکٔنۍ ',
      languagesCodeList[24]: 'سِندھی ',
      languagesCodeList[25]: 'سنتٲلۍ',
    },
    // Konkani
    languagesCodeList[23]: {
      languagesCodeList[0]: 'इंग्लीश',
      languagesCodeList[1]: 'हिंदी',
      languagesCodeList[2]: 'मराठी',
      languagesCodeList[3]: 'बांगला',
      languagesCodeList[4]: 'पंजाबी',
      languagesCodeList[5]: 'गुजराती',
      languagesCodeList[6]: 'ओडिया',
      languagesCodeList[7]: 'तामीळ',
      languagesCodeList[8]: 'तेलगु',
      languagesCodeList[9]: 'कन्नडा',
      languagesCodeList[10]: 'उर्दू',
      languagesCodeList[11]: 'डोंगरी',
      languagesCodeList[12]: 'नेपाळी',
      languagesCodeList[13]: 'सिंहली',
      languagesCodeList[14]: 'संस्कृत',
      languagesCodeList[15]: 'आसामीज',
      languagesCodeList[16]: 'मैथिली',
      languagesCodeList[17]: 'भोजपुरी',
      languagesCodeList[18]: 'मलयाळम',
      languagesCodeList[19]: 'राजस्थानी',
      languagesCodeList[20]: 'बोडो',
      languagesCodeList[21]: 'मणिपुरी',
      languagesCodeList[22]: 'कश्मिरी',
      languagesCodeList[23]: 'कोंकणी',
      languagesCodeList[24]: 'सिधीं',
      languagesCodeList[25]: 'संथाली',
    },
    // Sindhi
    languagesCodeList[24]: {
      languagesCodeList[0]: 'अंग्रेज़ी',
      languagesCodeList[1]: 'हिंदी',
      languagesCodeList[2]: 'मराठी',
      languagesCodeList[3]: 'बांगला',
      languagesCodeList[4]: 'पंजाबी',
      languagesCodeList[5]: 'गुजराती',
      languagesCodeList[6]: 'ओडिया',
      languagesCodeList[7]: 'तमील',
      languagesCodeList[8]: 'तेलगू',
      languagesCodeList[9]: 'कन्नड़',
      languagesCodeList[10]: 'उर्दू',
      languagesCodeList[11]: 'डोंगरी',
      languagesCodeList[12]: 'नेपाली',
      languagesCodeList[13]: 'सिंहली',
      languagesCodeList[14]: 'संस्कृत',
      languagesCodeList[15]: 'असमी',
      languagesCodeList[16]: 'मैथिली',
      languagesCodeList[17]: 'भोजपुरी',
      languagesCodeList[18]: 'मलयालम',
      languagesCodeList[19]: 'राजस्थानी',
      languagesCodeList[20]: 'बोडो',
      languagesCodeList[21]: 'मणिपुरी',
      languagesCodeList[22]: 'कशमीरी',
      languagesCodeList[23]: 'कोंकणी',
      languagesCodeList[24]: 'सिंधी',
      languagesCodeList[25]: 'संथली',
    },
    // Santali
    languagesCodeList[25]: {
      languagesCodeList[0]: 'ᱤᱝᱞᱤᱥ',
      languagesCodeList[1]: 'ᱦᱤᱱᱫᱤ ',
      languagesCodeList[2]: 'ᱢᱟᱨᱟᱴᱷᱤ ',
      languagesCodeList[3]: 'ᱵᱟᱝᱞᱟ',
      languagesCodeList[4]: 'ᱯᱟᱧᱡᱟᱵᱤ',
      languagesCodeList[5]: 'ᱜᱩᱡᱨᱟᱴᱤ',
      languagesCodeList[6]: 'ᱳᱰᱤᱭᱟ',
      languagesCodeList[7]: 'ᱛᱟᱢᱤᱞ ',
      languagesCodeList[8]: 'ᱛᱮᱞᱩᱜᱩ',
      languagesCodeList[9]: 'ᱠᱟᱱᱱᱟᱰᱟ',
      languagesCodeList[10]: 'ᱩᱨᱫᱷᱩ',
      languagesCodeList[11]: 'ᱰᱳᱜᱨᱤ',
      languagesCodeList[12]: 'ᱱᱮᱯᱟᱞᱤ',
      languagesCodeList[13]: 'ᱥᱤᱱᱦᱚᱞ',
      languagesCodeList[14]: 'ᱥᱚᱝᱚᱥᱠᱨᱤᱛ',
      languagesCodeList[15]: 'ᱟᱥᱟᱢᱤᱥ',
      languagesCodeList[16]: 'ᱢᱟᱭᱛᱷᱤᱞᱤ',
      languagesCodeList[17]: 'ᱵᱷᱳᱡᱯᱩᱨᱤ',
      languagesCodeList[18]: 'ᱢᱟᱞᱟᱭᱟᱞᱚᱢ ',
      languagesCodeList[19]: 'ᱨᱟᱡᱚᱥᱛᱷᱟᱱᱤ',
      languagesCodeList[20]: 'ᱵᱳᱰᱳ ',
      languagesCodeList[21]: 'ᱢᱩᱱᱤᱯᱩᱨᱤ',
      languagesCodeList[22]: 'ᱠᱟᱥᱢᱤᱨᱤ',
      languagesCodeList[23]: 'ᱠᱳᱝᱠᱚᱱᱤ',
      languagesCodeList[24]: 'ᱥᱤᱱᱫᱷᱤ',
      languagesCodeList[25]: 'ᱥᱟᱱᱛᱟᱲᱤ',
    },
  };
}
